"""
SparkAI Engine Package

Core engine providing ECS architecture, scene management,
and AI-native game development capabilities.
"""

from sparkai.engine.engine import SparkEngine
from sparkai.engine.ecs import (
    Component,
    ComponentRegistry,
    Entity,
    EntityManager,
    System,
    SystemPriority,
    SystemRegistry,
    SystemScheduler,
    World,
)
from sparkai.engine.ecs.components import (
    Transform,
    Renderable,
    SpriteRenderer,
    TextRenderer,
    PhysicsBody,
    Collider,
    Camera,
    AudioSource,
    Animator,
    InputReceiver,
    AIBrain,
    Script,
    Tween,
)
from sparkai.engine.ecs.systems import (
    TransformSystem,
    PhysicsSystem,
    RenderSystem,
    AnimationSystem,
    AudioSystem,
    InputSystem,
    AISystem,
    TweenSystem,
    ScriptSystem,
    CollisionSystem,
)
from sparkai.engine.ecs.resource import (
    Resource,
    ResourceManager,
    ResourceType,
)

# --- Engine Module Imports ---

from sparkai.engine.engine_collision_system import (
    CollisionBody,
    CollisionLayer,
    CollisionResult,
    CollisionShape as CollisionSystemShape,
    EngineCollisionSystem,
    get_collision_system,
)
from sparkai.engine.engine_game_loop import (
    EngineGameLoop,
    FrameTiming,
    LoopState,
    UpdateLayer,
    get_game_loop,
)
from sparkai.engine.engine_resource_cache import (
    EngineResourceCache,
    ResourceGroup,
    ResourceHandle,
    ResourceState as CacheResourceState,
    ResourceType as CacheResourceType,
    get_resource_cache,
)
from sparkai.engine.engine_scene_graph import (
    SceneGraphEngine,
    GraphNode as SceneGraphNode,
    Transform3D as SceneTransform3D,
    Quaternion,
    Vector3 as SceneVector3,
    get_scene_graph,
)
from sparkai.engine.engine_script_engine import (
    EngineScriptEngine,
    ScriptBinding,
    ScriptContext,
    ScriptEvent,
    ScriptExpression,
    ScriptLanguage as ScriptEngineLanguage,
    get_script_engine,
)
from sparkai.engine.engine_spatial_hash import (
    EngineSpatialHash,
    SpatialObject,
    SpatialQuery,
    get_spatial_hash,
)
from sparkai.engine.engine_particle_system import (
    EmitterConfig,
    EmitterLifetime,
    EmitterState,
    EmissionShape,
    EngineParticleSystem,
    Particle,
    ParticleBlendMode,
    ParticleReport,
    SimulationSpace,
    get_particle_system,
)
from sparkai.engine.engine_terrain_system import (
    BiomeLayer,
    ChunkState as TerrainChunkState,
    EngineTerrainSystem,
    ErosionSettings,
    ErosionType,
    TerrainAlgorithm,
    TerrainChunk,
    TerrainConfig,
    TerrainStats,
    TextureLayer,
    get_terrain_system,
)
from sparkai.engine.engine_sprite_batcher import (
    AtlasPackMode,
    AtlasRegion,
    BatchKey,
    BatchStrategy,
    BlendMode as SpriteBlendMode,
    EngineSpriteBatcher,
    SortMode,
    SpriteBatch,
    SpriteDrawCommand,
    TextureAtlas as BatcherTextureAtlas,
    get_sprite_batcher,
)
from sparkai.engine.engine_object_pool import (
    AllocationPolicy,
    EngineObjectPool,
    ObjectState,
    PoolConfig,
    PoolStats,
    PoolStrategy,
    PooledObject,
    WarmupMode,
    get_object_pool,
)
from sparkai.engine.engine_runtime_scripting import (
    EngineRuntimeScripting,
    ExecutionMode as RuntimeExecutionMode,
    ScriptDefinition,
    ScriptEventType,
    ScriptExecutionContext,
    ScriptInstance,
    ScriptLanguage as RuntimeScriptLanguage,
    ScriptSandbox,
    ScriptScope,
    ScriptState,
    get_runtime_scripting,
)
from sparkai.engine.engine_procedural_animation import (
    AnimationBlend,
    AnimationBlendMode as ProceduralBlendMode,
    Bone,
    BoneConstraintType,
    EngineProceduralAnimation,
    IKMethod,
    IKTarget,
    MotionStyle,
    ProceduralEffectType,
    ProceduralMotion,
    Skeleton,
    get_procedural_animation,
)
from sparkai.engine.engine_scene_transition import (
    EngineSceneTransition,
    SceneDescriptor,
    SceneInstance,
    SceneLoadMode,
    SceneState,
    SceneStats,
    TransitionConfig,
    TransitionDirection,
    TransitionEffect,
    TransitionResult,
    TransitionState,
    get_scene_transition,
)
from sparkai.engine.engine_animation_controller import (
    AnimationBlendMode as ControllerBlendMode,
    AnimationClip as ControllerAnimationClip,
    AnimationEvent,
    AnimationEventType,
    AnimationFrame as ControllerAnimationFrame,
    AnimationInstance,
    AnimationParameter,
    AnimationPlayMode as ControllerPlayMode,
    AnimationState,
    AnimationTransition,
    EngineAnimationController,
    StateMachine,
    TransitionCondition,
    TransitionConditionData,
    get_animation_controller,
)
from sparkai.engine.engine_input_mapping import (
    InputDevice,
    InputAction,
    GestureType,
    InputBinding,
    ControlScheme,
    GesturePattern,
    InputBufferEntry,
    InputMappingEngine,
    get_input_mapping_engine,
)
from sparkai.engine.engine_node_composer import (
    EngineNodeComposer,
    NodeGroup,
    NodeSignal,
    NodeState,
    NodeType as NodeComposerNodeType,
    NodeTree,
    SceneNode as ComposerSceneNode,
    SignalDirection,
    Transform2D as ComposerTransform2D,
    get_node_composer,
)
from sparkai.engine.engine_visual_event_sheet import (
    ActionType as EventSheetActionType,
    ConditionEvaluator,
    ConditionOperator,
    EngineVisualEventSheet,
    EventAction as VisualEventAction,
    EventCondition as VisualEventCondition,
    EventGroup,
    EventScope,
    EventSheet as VisualEventSheet,
    EventTrigger,
    GameEvent,
    SheetStatus,
    SubEvent,
    get_visual_event_sheet,
)
from sparkai.engine.engine_fluid_dynamics import (
    BoundaryType,
    EngineFluidDynamics,
    FluidBoundary,
    FluidConfig,
    FluidInteraction,
    FluidParticle,
    FluidSimulation,
    FluidType,
    InteractionMode,
    SimulationStats,
    SolverType,
    get_fluid_dynamics,
)
from sparkai.engine.engine_crowd_dynamics import (
    AvoidanceStrategy,
    CrowdAgent,
    CrowdBehavior,
    CrowdDensityLevel,
    CrowdDensityRegion,
    CrowdEvent,
    CrowdGroup,
    EngineCrowdDynamics,
    FlowField as CrowdFlowField,
    FormationType,
    SimulationFrame,
    get_crowd_dynamics,
)
from sparkai.engine.engine_skeletal_blending import (
    AnimationClip as SkeletalAnimationClip,
    AnimationLayer,
    AnimationWrapMode,
    BlendSpace,
    BlendSpaceDimension,
    BlendSpaceSample,
    BlendState,
    BlendType,
    BoneNode,
    BoneSpace,
    BoneTransform,
    EngineSkeletalBlending,
    IKAlgorithm,
    IKChain,
    Keyframe,
    LayerBlendMode,
    get_skeletal_blending,
)
from sparkai.engine.engine_gpu_compute import (
    BufferAccess,
    BufferType,
    ComputeBuffer,
    ComputeDimension,
    ComputeDispatch,
    ComputeKernel,
    ComputePipeline,
    EngineGPUCompute,
    KernelStatus,
    OccupancyLevel,
    PipelineBarrier,
    WorkgroupConfig,
    get_gpu_compute,
)
from sparkai.engine.engine_deterministic_core import (
    DesyncReport,
    DesyncSeverity,
    EngineDeterministicCore,
    FrameStatus,
    InputSource,
    ReplayFrame,
    SimFrame,
    SimInput,
    StateHashNode,
    SyncMode,
    get_deterministic_core,
)
from sparkai.engine.engine_weather_system import (
    DayNightCycle,
    Season,
    TimeOfDay,
    WeatherCondition,
    WeatherEffect,
    WeatherIntensity,
    WeatherSystemEngine,
    WeatherType,
    get_weather_system,
)
from sparkai.engine.engine_water_simulation import (
    BuoyantObject,
    EngineWaterSimulation,
    SplashParticle,
    SplashType,
    WaterBody,
    WaterBodyType,
    WaterSurface,
    WavePattern,
    WavePoint,
    get_water_simulation,
)
from sparkai.engine.engine_audio_synthesis import (
    AudioSample,
    EffectConfig,
    EffectType,
    EngineAudioSynthesis,
    EnvelopeConfig,
    FilterConfig,
    FilterType as SynthesisFilterType,
    ModulationConfig,
    ModulationTarget,
    NoiseColor,
    NoteEvent,
    NoteName,
    OscillatorConfig,
    ScaleType,
    WaveformType,
    get_audio_synthesis,
)
from sparkai.engine.engine_physics_dynamics import (
    AABB,
    BodyType,
    CollisionShape as PhysicsCollisionShape,
    CollisionState,
    Contact,
    EnginePhysicsDynamics,
    Joint,
    PhysicsContact,
    RigidBody,
    ShapeType,
    Vector2,
    get_physics_dynamics,
)
from sparkai.engine.engine_world_streamer import (
    ChunkState as StreamerChunkState,
    DetailLevel,
    EngineWorldStreamer,
    LoadPriority,
    StreamingConfig,
    StreamingRegion,
    StreamingStrategy,
    WorldChunk as StreamerWorldChunk,
    get_world_streamer,
)
from sparkai.engine.engine_pathfinding import (
    AlgorithmType,
    DynamicObstacle,
    EnginePathfinding,
    FlowField as PathFlowField,
    GridConfig,
    GridNode,
    HeuristicType,
    MovementPenalty,
    NavMeshPolygon,
    PathResult,
    PathResultData,
    SteeringBehavior,
    get_pathfinding_engine,
)
from sparkai.engine.engine_camera_controller import (
    CameraConfig,
    CameraMode,
    CameraProjection,
    CameraState,
    CameraTarget,
    CinematicKeyframe,
    CinematicSequence,
    DeadZoneShape,
    EngineCameraController,
    FollowStyle,
    ShakeConfig,
    ShakeProfile,
    TransitionType as CameraTransitionType,
    get_camera_controller,
)
from sparkai.engine.engine_frame_timer import (
    EngineFrameTimer,
    FramePacingMode,
    FrameSnapshot,
    FrameTimingStats,
    TimerState,
    get_frame_timer,
)
from sparkai.engine.engine_platform_layer import (
    AudioBackend,
    DisplayConfig,
    DisplayMode,
    EnginePlatformLayer,
    InputDevice as PlatformInputDevice,
    InputProfile,
    PlatformCapabilities,
    RenderBackend,
    TargetPlatform,
    get_platform_layer,
)
from sparkai.engine.engine_mega_sprite_layer import (
    EngineMegaSpriteLayer,
    GPUBufferStrategy,
    GPUVertexBatch,
    MegaSpriteBlendMode,
    MegaSpriteInstance,
    MegaSpriteLayerConfig,
    MegaSpriteSortMode,
    get_mega_sprite_layer,
)
from sparkai.engine.engine_server_orchestrator import (
    CommandPriority,
    CommandQueue,
    EngineServerOrchestrator,
    ResourceHandle,
    ResourceType as OrchestratorResourceType,
    ServerHealthMetric,
    ServerInstance,
    ServerStatus,
    ServerType,
    get_engine_server_orchestrator,
)
from sparkai.engine.engine_rid_allocator import (
    EngineRIDAllocator,
    RIDHandle,
    RIDPoolStats,
    RIDResourceType,
    RIDState,
    get_rid_allocator,
)
from sparkai.engine.engine_event_scripting import (
    ActionType as EventScriptActionType,
    ConditionType,
    EngineEventScripting,
    EventAction as ScriptingEventAction,
    EventCondition as ScriptingEventCondition,
    EventLink,
    EventSheet as ScriptingEventSheet,
    EventVariable,
    LinkType as EventLinkType,
    OperatorType,
    VariableScope,
    get_engine_event_scripting,
)
from sparkai.engine.engine_gpu_batch_rendering import (
    BatchType,
    BlendMode as GPUBlendMode,
    CullMode,
    EngineGPUBatchRendering,
    GPUProfile,
    LODLevel,
    RenderBatch,
    SortOrder,
    SpriteInstance,
    SpriteLayerConfig,
    TileLayerConfig,
    get_gpu_batch_rendering,
)
from sparkai.engine.engine_audio_spatial import (
    AudioListener,
    AudioOcclusion,
    AudioReverbZone,
    AudioSource as SpatialAudioSource,
    AudioSourceType,
    EngineAudioSpatial,
    FilterType as SpatialFilterType,
    PlaybackState,
    ProceduralSound,
    ReverbPreset,
    RolloffMode,
    WaveformType as SpatialWaveformType,
    get_audio_spatial,
)
from sparkai.engine.engine_behavior_orchestrator import (
    BehaviorContext,
    BehaviorNode,
    BehaviorResult,
    BehaviorTransition,
    BehaviorTree,
    EngineBehaviorOrchestrator,
    NodeType as BehaviorNodeType,
    TransitionType as BehaviorTransitionType,
    get_engine_behavior_orchestrator,
)
from sparkai.engine.engine_procedural_world import (
    BiomeType,
    DungeonStyle,
    EngineProceduralWorld,
    GeneratedDungeon,
    GeneratedStructure,
    GeneratedWorld,
    GenerationAlgorithm as WorldGenerationAlgorithm,
    SettlementType,
    TerrainType,
    WorldConfig,
    WorldTile,
    get_procedural_world,
)
from sparkai.engine.engine_render_pipeline import (
    BlendOperation as PipelineBlendMode,
    CullingMode,
    FrameSnapshot,
    PostEffect,
    PostEffectKind,
    QualityTier,
    RenderPass,
    RenderPassType,
    RenderPipeline,
    get_render_pipeline,
)
from sparkai.engine.engine_ai_system import (
    GameAISystem,
    NavMeshGenerator, NavMeshAreaType, NavMeshLink,
    PathfindingEngine, PathfindHeuristic,
    BehaviorTreeRuntime, BehaviorNodeKind, DecoratorKind, BehaviorResult,
    AIPerceptionSystem, PerceptionSense, PerceptionEvent,
    StateMachineAI, AIState, AIStateTransition,
    get_ai_system,
)
from sparkai.engine.engine_animation_system import (
    AnimationClip as SystemAnimationClip,
    AnimationFrame as SystemAnimationFrame,
    AnimationPlayMode as SystemPlayMode,
    EasingFunction,
    EngineAnimationSystem,
    InterpolationMode,
    KeyframeSequence,
    SequenceKeyframe,
    TweenDefinition,
    get_animation_system,
)
from sparkai.engine.engine_scene_manager import (
    EasingType,
    EngineSceneManager,
    SceneDefinition,
    SceneLayer,
    SceneTransition as ManagerSceneTransition,
    SceneType,
    TransitionType as SceneTransitionType,
    get_scene_manager,
)
from sparkai.engine.engine_navigation_system import (
    EngineNavigationSystem,
    LinkType as NavLinkType,
    NavigationAgent,
    NavigationLink,
    NavigationMesh,
    NavigationPath,
    NavigationState,
    PathStatus,
    get_navigation_system,
)
from sparkai.engine.engine_visual_scripting import (
    ConnectionType,
    EngineVisualScripting,
    ExecutionContext,
    ExecutionMode as VisualExecutionMode,
    ImplementationType,
    NodeCategory,
    NodeConnection as VisualScriptConnection,
    NodePort,
    NodeTemplate,
    PortDataType,
    PortDirection,
    ScriptGraph as VisualScriptGraph,
    ScriptNode as VisualScriptNode,
    ScriptVariable,
    get_engine_visual_scripting,
)
from sparkai.engine.engine_entity_component_system import (
    Component as ECSComponent,
    ComponentBlueprint,
    ComponentCategory,
    ComponentUpdatePhase,
    EngineEntityComponentSystem,
    Entity as ECSEntity,
    EntityArchetype,
    System as ECSSystem,
    SystemExecutionOrder,
    World as ECSWorld,
    get_entity_component_system,
)
from sparkai.engine.engine_tilemap_runtime import (
    AutoTileConfig,
    EngineTileMapRuntime,
    RenderOrder,
    TileAnimationMode,
    TileBrush,
    TileCollisionShape,
    TileDefinition,
    TileLayer,
    TileLayerType,
    TileMap,
    Tileset,
    get_tilemap_runtime,
)
from sparkai.engine.engine_progressive_loading import (
    ChunkState as ProgressiveChunkState,
    EngineProgressiveLoading,
    LoadingQueue,
    LODTransition,
    PriorityLevel,
    StreamingConfig as ProgressiveStreamingConfig,
    StreamingPreset,
    WorldChunk as ProgressiveWorldChunk,
    get_progressive_loading,
)
from sparkai.engine.engine_adaptive_content import (
    AdaptiveDifficulty,
    ContentProfile,
    ContentType,
    ContentVariant,
    DifficultyTier,
    EngineAdaptiveContent,
    PlayerArchetype,
    get_adaptive_content_engine,
)
from sparkai.engine.engine_procedural_dungeon import (
    DungeonCorridor,
    DungeonLayout,
    DungeonRoom,
    DungeonTheme,
    DungeonThemeCategory,
    EncounterNode,
    EncounterType,
    EngineProceduralDungeon,
    GenerationAlgorithm as DungeonGenerationAlgorithm,
    RoomType,
    TreasureCategory,
    TreasureNode,
    get_procedural_dungeon_generator,
)
from sparkai.engine.engine_biome_generation import (
    BiomeDefinition,
    BiomeGenerationPipeline,
    ClimateBand,
    ClimateZone as BiomeClimateZone,
    FloraDensity,
    FloraTemplate,
    SoilType,
    TerrainCategory,
    TerrainLayer,
    WorldConfiguration,
    get_biome_generation_pipeline,
)
from sparkai.engine.engine_game_state_analyzer import (
    AnalysisDomain,
    BottleneckSeverity,
    EntityRelationship,
    EntityType as AnalyzerEntityType,
    GameStateAnalyzer,
    RelationshipType,
    SceneSnapshot,
    SceneStateCategory,
    SystemicInteraction,
    get_game_state_analyzer,
)
from sparkai.engine.engine_visual_script_runtime import (
    NodeConnection as ScriptRuntimeConnection,
    NodeParameter,
    NodeType as VisualScriptNodeType,
    ParameterType,
    ScriptGraph as ScriptRuntimeGraph,
    ScriptNode as ScriptRuntimeNode,
    TargetLanguage,
    ValidationIssue,
    ValidationResult,
    VisualScriptRuntime,
    get_visual_script_runtime,
)
from sparkai.engine.engine_texture_atlas import (
    AtlasFormat,
    AtlasPage,
    AtlasResizePolicy,
    PackingAlgorithm,
    PackResult,
    SpriteOrigin,
    SpriteRegion,
    TextureAtlas as AtlasTextureAtlas,
    get_texture_atlas,
)
from sparkai.engine.engine_extension_registry import (
    BehaviorModule,
    CompatibilityLevel,
    ExtensionDefinition,
    ExtensionDependency,
    ExtensionRegistry,
    ExtensionStatus,
    ExtensionType,
    ExtensionVersion,
    InstallSource,
    ObjectTypeModule,
    get_extension_registry,
)
from sparkai.engine.engine_node_editor import (
    NodeEditorEngine, NodeCategory, PortDirection, PortDataType,
    GraphExecutionState, NodePort, NodeConnection, GraphNode,
    NodeGraph, NodeTemplate,
    get_node_editor_engine,
)
from sparkai.engine.engine_scene_serializer import (
    SceneSerializerEngine, SerializationFormat, SceneVersion,
    DiffOperation, MergeStrategy, SceneData, SceneDiff,
    SceneSavePoint,
    get_scene_serializer_engine,
)
from sparkai.engine.engine_signal_bus import (
    SignalBus, SignalCategory, ConnectionState,
    SignalDefinition, SignalConnection, SignalEmission,
    get_signal_bus as get_engine_signal_bus,
)
from sparkai.engine.engine_ecosystem_dynamics import (
    EcosystemDynamicsEngine, SpeciesType, PopulationStatus, MigrationTrigger,
    SeasonType,
    SpeciesProfile, PopulationSnapshot, RegionEcosystem, MigrationEvent, EcosystemReport,
    get_ecosystem_dynamics,
)
from sparkai.engine.engine_civilization_evolution import (
    CivilizationEvolutionEngine, TechEra, GovernmentType, RelationStatus,
    CulturalAspect,
    TechnologyNode, CulturalIdentity, CivilizationState, DiplomaticEvent, CivilizationSnapshot,
    get_civilization_engine,
)
from sparkai.engine.engine_procedural_city import (
    ProceduralCityEngine, DistrictType, RoadType, BuildingType, CityStyle,
    RoadSegment, Building, District, CityLayout, CityGenerationConfig,
    get_procedural_city_engine,
)
from sparkai.engine.engine_flow_state_monitor import (
    FlowStateMonitorEngine, FlowState, ChallengeLevel, SkillLevel, SignalType,
    PlayerSignal, FlowReading, FlowHistory, AdaptationSuggestion, FlowProfile,
    get_flow_state_monitor,
)
from sparkai.engine.engine_physics import (
    PhysicsEngine, BodyType, CollisionShape, ConstraintType,
    Vector2D, PhysicsBody, CollisionEvent, PhysicsConstraint,
    get_physics_engine,
)
from sparkai.engine.engine_behavior import (
    BehaviorEngine, BTStatus, FSMStateType, BehaviorType,
    BTCondition, BTAction, BTNode, BehaviorTree,
    FSMTransition, FSMState, StateMachine,
    UtilityAction, UtilityAI,
    get_behavior_engine,
)
from sparkai.engine.engine_input import (
    InputEngine, InputDeviceType, InputEventType, GestureType, ActionTriggerType,
    InputEvent, InputAction, GestureEvent, InputState,
    get_input_engine,
)
from sparkai.engine.engine_scene_lifecycle import (
    SceneLifecycleEngine, SceneStatus, SceneLayer, TransitionType, NodeType, LifecycleHook,
    SceneNode, Scene, SceneTransition,
    get_scene_lifecycle_engine,
)
from sparkai.engine.engine_job_system import (
    JobSystemEngine, JobStatus, JobType, WorkerStatus, SchedulingPolicy,
    Job, JobQueue, JobResult, WorkerThread, JobGraph,
    get_job_system,
)
from sparkai.engine.engine_cloth_physics import (
    ClothPhysicsEngine, ClothSolverType, SoftBodyType, ConstraintType as ClothConstraintType,
    ClothParticle, ClothConstraint, ClothMesh, ClothMaterial, SoftBody, ClothCollisionSphere,
    get_cloth_physics,
)
from sparkai.engine.engine_lightmapping import (
    LightmappingEngine, BakeStatus, LightType, BakeQuality, GIAlgorithm,
    LightmapAtlas, LightmapRegion, LightProbe, LightProbeVolume,
    BakedLight, BakeSettings, BakedScene,
    get_lightmapping,
)
from sparkai.engine.engine_spatial_partition import (
    SpatialPartitionEngine, PartitionType, QueryType,
    BoundingBox, SpatialEntry, TreeNode, QueryResult,
    get_spatial_partition,
)
from sparkai.engine.engine_inverse_kinematics import (
    InverseKinematicsEngine, IKSolverType, JointType,
    ConstraintType as IKConstraintType, IKJoint, IKBoneChain, IKEffector, IKSolution,
    get_inverse_kinematics,
)
from sparkai.engine.engine_save_system import (
    SaveSystemEngine, SaveFormat, SaveSlotType, SaveStatus,
    SaveMetadata, SaveData, SaveSlot,
    get_save_system,
)
from sparkai.engine.engine_event_system import (
    EventSystemEngine, EventPriority, EventChannel, DispatchMode,
    GameEvent, EventListener, EventRecord,
    get_event_system,
)
from sparkai.engine.engine_fluid_simulation import (
    FluidSimulationEngine, FluidSolverType, BoundaryType, FluidDomain,
    FluidGrid, FluidParticle, FluidSource, FluidObstacle,
    get_fluid_simulation,
)
from sparkai.engine.engine_post_processing import (
    PostProcessingEngine, EffectType, BlendMode as PPBlendMode,
    QualityLevel, PipelineStage, PostProcessEffect, EffectParameter,
    PipelineConfig, EffectResult,
    get_post_processing,
)
from sparkai.engine.engine_ui_system import (
    UISystemEngine, WidgetType, LayoutType, AnchorPoint, UIEventType,
    ThemeMode, UIRect, UIColor, UITheme, UIWidget, UICanvas, UIEvent, UIState,
    get_ui_system,
)
from sparkai.engine.engine_network_sync import (
    NetworkSyncEngine, SyncAuthority, SyncStrategy, ConnectionState,
    SyncChannel, MessagePriority, NetworkEntity, SyncMessage,
    ConnectionInfo, SyncSnapshot, SyncSession,
    get_network_sync,
)
from sparkai.engine.engine_performance_monitor import (
    PerformanceMonitorEngine, MonitorDomain, AlertCondition, MonitorState,
    ProfilerMode, MonitorSample, MonitorAlert, ProfileSession, FrameReport,
    get_performance_monitor,
)
from sparkai.engine.engine_entity_component import (
    EntityComponentEngine,
    Component as EntityComponentBase,
    Entity as EntityComponentEntity,
    System as EntityComponentSystem,
    ComponentManager,
    SystemManager,
    SystemExecutionPhase,
    EntityState as EntityComponentState,
    QueryResult,
    ComponentStorageType,
    get_entity_component_engine,
)
from sparkai.engine.engine_spatial_audio import (
    SpatialAudioEngine,
    AudioSource3D,
    AudioListener as SpatialAudioListener,
    AudioOcclusionModel,
    AudioReverbZone as SpatialAudioReverbZone,
    DopplerEffect,
    AudioMixer,
    AudioChannel,
    AudioSourceShape,
    RolloffMode as SpatialRolloffMode,
    ReverbPreset as SpatialReverbPreset,
    MixerBusType,
    OcclusionMethod,
    get_spatial_audio_engine,
)
from sparkai.engine.engine_level_streaming import (
    LevelStreamingEngine,
    StreamingCell,
    CellLoader,
    LODController,
    StreamingPriorityQueue,
    PreloadPredictor,
    CellState as StreamingCellState,
    DetailLevel as StreamingDetailLevel,
    LoadPriority as StreamingLoadPriority,
    StreamingStrategy as StreamingEngineStrategy,
    PreloadDirection,
    get_level_streaming_engine,
)
from sparkai.engine.engine_dynamic_weather import (
    DynamicWeatherEngine,
    WeatherProfile,
    WeatherTransition,
    WeatherZone,
    WeatherParticleSystem,
    WeatherParticle,
    AtmosphereSimulator,
    WeatherType as DynamicWeatherType,
    PrecipitationType,
    TransitionCurve,
    ScatteringModel,
    CloudType,
    get_dynamic_weather_engine,
)
from sparkai.engine.engine_procedural_terrain import (
    ProceduralTerrainEngine,
    NoiseGenerator,
    HeightmapGenerator,
    ErosionSimulator,
    BiomeMapper,
    TerrainMeshBuilder,
    TerrainChunk as ProceduralTerrainChunk,
    NoiseType,
    TerrainLOD,
    ErosionMode,
    BiomeType as ProceduralBiomeType,
    ChunkState as ProceduralChunkState,
    get_procedural_terrain_engine,
)
from sparkai.engine.engine_destruction_system import (
    DestructionPhysicsEngine,
    FracturePattern,
    VoronoiFracture,
    DestructionPhysics,
    StructuralIntegrity,
    DebrisPool,
    FractureStyle,
    MaterialStrength,
    DebrisState,
    StructureType,
    CollapseMode,
    get_destruction_physics_engine,
)
from sparkai.engine.engine_behavior_composer import (
    BehaviorComposerEngine,
    BehaviorTemplate,
    BehaviorInstance,
    BehaviorComposition,
    BehaviorCategory,
    BehaviorPriority,
    BehaviorLifecycle,
    CompositionMode,
    get_behavior_composer,
)
from sparkai.engine.engine_asset_compiler import (
    AssetCompilerEngine,
    AssetType,
    AssetFormat,
    AssetSource,
    CompileResult,
    AssetBundle,
    CompileConfig,
    CompileStatus,
    CompressionLevel,
    BundleStrategy,
    get_asset_compiler,
)
from sparkai.engine.engine_unified_runtime import (
    UnifiedGameRuntime, RuntimeState, TimestepMode, SceneState,
    RenderPhase, PhysicsStep, AudioChannel, InputLayer,
    FrameTiming, SceneInstance, RenderStats, PhysicsStats,
    AudioStats, RuntimeProfile, GameLoopOrchestrator,
    SceneLifecycleManager, PhysicsCoordinator, RenderPipelineManager,
    AudioMixer, InputAggregator, EntityCoordinator, PerformanceProfiler,
    get_unified_runtime,
)
from sparkai.engine.engine_adaptive_rendering import (
    AdaptiveRenderingEngine,
    QualityTier,
    RenderFeature,
    AdaptationStrategy,
    PerformanceMetrics,
    QualityPreset,
    AdaptationEvent,
    MetricsCollector,
    QualityManager,
    get_adaptive_rendering,
)
from sparkai.engine.engine_physics_optimizer import (
    PhysicsOptimizerEngine,
    PhysicsSolverType,
    SpatialStrategy,
    OptimizationTarget,
    PhysicsQualityLevel,
    PhysicsProfile,
    PhysicsConfiguration,
    OptimizationRecommendation,
    SpatialOptimizer,
    SolverOptimizer,
    get_physics_optimizer,
)
from sparkai.engine.engine_ai_native_core import (
    AINativeEngineCore,
    EngineMode,
    EngineCommand,
    EngineEventType,
    EntityCategory,
    EngineStateSnapshot,
    EngineCommandResult,
    EngineEvent,
    OptimizationProfile,
    GameCreationSpec,
    get_ai_native_engine,
)
from sparkai.engine.engine_server_registry import (
    ServerRegistry, ServerType, ServerStatus, ServerPriority,
    ServerConfig, ServerInfo,
    get_engine_server_registry,
)
from sparkai.engine.engine_scene_tree import (
    SceneTree, SceneNode, NodeType, NodeLifecycle,
    get_scene_tree,
)
from sparkai.engine.engine_component_system import (
    ComponentRegistry as GameComponentRegistry,
    ComponentCategory, ComponentLifecycle, ComponentDefinition,
    ComponentInstance, GameEntity,
    get_component_registry,
)


__all__ = [
    # Existing
    "SparkEngine",
    "Component",
    "ComponentRegistry",
    "Entity",
    "EntityManager",
    "System",
    "SystemPriority",
    "SystemRegistry",
    "SystemScheduler",
    "World",
    "Transform",
    "Renderable",
    "SpriteRenderer",
    "TextRenderer",
    "PhysicsBody",
    "Collider",
    "Camera",
    "AudioSource",
    "Animator",
    "InputReceiver",
    "AIBrain",
    "Script",
    "Tween",
    "TransformSystem",
    "PhysicsSystem",
    "RenderSystem",
    "AnimationSystem",
    "AudioSystem",
    "InputSystem",
    "AISystem",
    "TweenSystem",
    "ScriptSystem",
    "CollisionSystem",
    "Resource",
    "ResourceManager",
    "ResourceType",
    # engine_collision_system
    "CollisionBody",
    "CollisionLayer",
    "CollisionResult",
    "CollisionSystemShape",
    "EngineCollisionSystem",
    "get_collision_system",
    # engine_game_loop
    "EngineGameLoop",
    "FrameTiming",
    "LoopState",
    "UpdateLayer",
    "get_game_loop",
    # engine_resource_cache
    "EngineResourceCache",
    "ResourceGroup",
    "ResourceHandle",
    "CacheResourceState",
    "CacheResourceType",
    "get_resource_cache",
    # engine_scene_graph
    "SceneGraphEngine",
    "SceneGraphNode",
    "SceneTransform3D",
    "Quaternion",
    "SceneVector3",
    "get_scene_graph",
    # engine_script_engine
    "EngineScriptEngine",
    "ScriptBinding",
    "ScriptContext",
    "ScriptEvent",
    "ScriptExpression",
    "ScriptEngineLanguage",
    "get_script_engine",
    # engine_spatial_hash
    "EngineSpatialHash",
    "SpatialObject",
    "SpatialQuery",
    "get_spatial_hash",
    # engine_particle_system
    "EmitterConfig",
    "EmitterLifetime",
    "EmitterState",
    "EmissionShape",
    "EngineParticleSystem",
    "Particle",
    "ParticleBlendMode",
    "ParticleReport",
    "SimulationSpace",
    "get_particle_system",
    # engine_terrain_system
    "BiomeLayer",
    "EngineTerrainSystem",
    "ErosionSettings",
    "ErosionType",
    "TerrainAlgorithm",
    "TerrainChunk",
    "TerrainChunkState",
    "TerrainConfig",
    "TerrainStats",
    "TextureLayer",
    "get_terrain_system",
    # engine_sprite_batcher
    "AtlasPackMode",
    "AtlasRegion",
    "BatchKey",
    "BatchStrategy",
    "SpriteBlendMode",
    "EngineSpriteBatcher",
    "SortMode",
    "SpriteBatch",
    "SpriteDrawCommand",
    "BatcherTextureAtlas",
    "get_sprite_batcher",
    # engine_object_pool
    "AllocationPolicy",
    "EngineObjectPool",
    "ObjectState",
    "PoolConfig",
    "PoolStats",
    "PoolStrategy",
    "PooledObject",
    "WarmupMode",
    "get_object_pool",
    # engine_runtime_scripting
    "EngineRuntimeScripting",
    "RuntimeExecutionMode",
    "ScriptDefinition",
    "ScriptEventType",
    "ScriptExecutionContext",
    "ScriptInstance",
    "RuntimeScriptLanguage",
    "ScriptSandbox",
    "ScriptScope",
    "ScriptState",
    "get_runtime_scripting",
    # engine_procedural_animation
    "AnimationBlend",
    "ProceduralBlendMode",
    "Bone",
    "BoneConstraintType",
    "EngineProceduralAnimation",
    "IKMethod",
    "IKTarget",
    "MotionStyle",
    "ProceduralEffectType",
    "ProceduralMotion",
    "Skeleton",
    "get_procedural_animation",
    # engine_scene_transition
    "EngineSceneTransition",
    "SceneDescriptor",
    "SceneInstance",
    "SceneLoadMode",
    "SceneState",
    "SceneStats",
    "TransitionConfig",
    "TransitionDirection",
    "TransitionEffect",
    "TransitionResult",
    "TransitionState",
    "get_scene_transition",
    # engine_animation_controller
    "ControllerBlendMode",
    "ControllerAnimationClip",
    "AnimationEvent",
    "AnimationEventType",
    "ControllerAnimationFrame",
    "AnimationInstance",
    "AnimationParameter",
    "ControllerPlayMode",
    "AnimationState",
    "AnimationTransition",
    "EngineAnimationController",
    "StateMachine",
    "TransitionCondition",
    "TransitionConditionData",
    "get_animation_controller",
    # engine_input_mapping
    "InputDevice",
    "InputAction",
    "GestureType",
    "InputBinding",
    "ControlScheme",
    "GesturePattern",
    "InputBufferEntry",
    "InputMappingEngine",
    "get_input_mapping_engine",
    # engine_node_composer
    "EngineNodeComposer",
    "NodeGroup",
    "NodeSignal",
    "NodeState",
    "NodeComposerNodeType",
    "NodeTree",
    "ComposerSceneNode",
    "SignalDirection",
    "ComposerTransform2D",
    "get_node_composer",
    # engine_visual_event_sheet
    "EventSheetActionType",
    "ConditionEvaluator",
    "ConditionOperator",
    "EngineVisualEventSheet",
    "VisualEventAction",
    "VisualEventCondition",
    "EventGroup",
    "EventScope",
    "VisualEventSheet",
    "EventTrigger",
    "GameEvent",
    "SheetStatus",
    "SubEvent",
    "get_visual_event_sheet",
    # engine_fluid_dynamics
    "BoundaryType",
    "EngineFluidDynamics",
    "FluidBoundary",
    "FluidConfig",
    "FluidInteraction",
    "FluidParticle",
    "FluidSimulation",
    "FluidType",
    "InteractionMode",
    "SimulationStats",
    "SolverType",
    "get_fluid_dynamics",
    # engine_crowd_dynamics
    "AvoidanceStrategy",
    "CrowdAgent",
    "CrowdBehavior",
    "CrowdDensityLevel",
    "CrowdDensityRegion",
    "CrowdEvent",
    "CrowdGroup",
    "CrowdFlowField",
    "EngineCrowdDynamics",
    "FormationType",
    "SimulationFrame",
    "get_crowd_dynamics",
    # engine_skeletal_blending
    "SkeletalAnimationClip",
    "AnimationLayer",
    "AnimationWrapMode",
    "BlendSpace",
    "BlendSpaceDimension",
    "BlendSpaceSample",
    "BlendState",
    "BlendType",
    "BoneNode",
    "BoneSpace",
    "BoneTransform",
    "EngineSkeletalBlending",
    "IKAlgorithm",
    "IKChain",
    "Keyframe",
    "LayerBlendMode",
    "get_skeletal_blending",
    # engine_gpu_compute
    "BufferAccess",
    "BufferType",
    "ComputeBuffer",
    "ComputeDimension",
    "ComputeDispatch",
    "ComputeKernel",
    "ComputePipeline",
    "EngineGPUCompute",
    "KernelStatus",
    "OccupancyLevel",
    "PipelineBarrier",
    "WorkgroupConfig",
    "get_gpu_compute",
    # engine_deterministic_core
    "DesyncReport",
    "DesyncSeverity",
    "EngineDeterministicCore",
    "FrameStatus",
    "InputSource",
    "ReplayFrame",
    "SimFrame",
    "SimInput",
    "StateHashNode",
    "SyncMode",
    "get_deterministic_core",
    # engine_weather_system
    "DayNightCycle",
    "Season",
    "TimeOfDay",
    "WeatherCondition",
    "WeatherEffect",
    "WeatherIntensity",
    "WeatherSystemEngine",
    "WeatherType",
    "get_weather_system",
    # engine_water_simulation
    "BuoyantObject",
    "EngineWaterSimulation",
    "SplashParticle",
    "SplashType",
    "WaterBody",
    "WaterBodyType",
    "WaterSurface",
    "WavePattern",
    "WavePoint",
    "get_water_simulation",
    # engine_audio_synthesis
    "AudioSample",
    "EffectConfig",
    "EffectType",
    "EngineAudioSynthesis",
    "EnvelopeConfig",
    "FilterConfig",
    "SynthesisFilterType",
    "ModulationConfig",
    "ModulationTarget",
    "NoiseColor",
    "NoteEvent",
    "NoteName",
    "OscillatorConfig",
    "ScaleType",
    "WaveformType",
    "get_audio_synthesis",
    # engine_physics_dynamics
    "AABB",
    "BodyType",
    "PhysicsCollisionShape",
    "CollisionState",
    "Contact",
    "EnginePhysicsDynamics",
    "Joint",
    "PhysicsContact",
    "RigidBody",
    "ShapeType",
    "Vector2",
    "get_physics_dynamics",
    # engine_world_streamer
    "StreamerChunkState",
    "DetailLevel",
    "EngineWorldStreamer",
    "LoadPriority",
    "StreamingConfig",
    "StreamingRegion",
    "StreamingStrategy",
    "StreamerWorldChunk",
    "get_world_streamer",
    # engine_pathfinding
    "AlgorithmType",
    "DynamicObstacle",
    "EnginePathfinding",
    "PathFlowField",
    "GridConfig",
    "GridNode",
    "HeuristicType",
    "MovementPenalty",
    "NavMeshPolygon",
    "PathResult",
    "PathResultData",
    "SteeringBehavior",
    "get_pathfinding_engine",
    # engine_camera_controller
    "CameraConfig",
    "CameraMode",
    "CameraProjection",
    "CameraState",
    "CameraTarget",
    "CinematicKeyframe",
    "CinematicSequence",
    "DeadZoneShape",
    "EngineCameraController",
    "FollowStyle",
    "ShakeConfig",
    "ShakeProfile",
    "CameraTransitionType",
    "get_camera_controller",
    # engine_frame_timer
    "EngineFrameTimer",
    "FramePacingMode",
    "FrameSnapshot",
    "FrameTimingStats",
    "TimerState",
    "get_frame_timer",
    # engine_platform_layer
    "AudioBackend",
    "DisplayConfig",
    "DisplayMode",
    "EnginePlatformLayer",
    "PlatformInputDevice",
    "InputProfile",
    "PlatformCapabilities",
    "RenderBackend",
    "TargetPlatform",
    "get_platform_layer",
    # engine_mega_sprite_layer
    "EngineMegaSpriteLayer",
    "GPUBufferStrategy",
    "GPUVertexBatch",
    "MegaSpriteBlendMode",
    "MegaSpriteInstance",
    "MegaSpriteLayerConfig",
    "MegaSpriteSortMode",
    "get_mega_sprite_layer",
    # engine_server_orchestrator
    "CommandPriority",
    "CommandQueue",
    "EngineServerOrchestrator",
    "ResourceHandle",
    "OrchestratorResourceType",
    "ServerHealthMetric",
    "ServerInstance",
    "ServerStatus",
    "ServerType",
    "get_engine_server_orchestrator",
    # engine_rid_allocator
    "EngineRIDAllocator",
    "RIDHandle",
    "RIDPoolStats",
    "RIDResourceType",
    "RIDState",
    "get_rid_allocator",
    # engine_event_scripting
    "EventScriptActionType",
    "ConditionType",
    "EngineEventScripting",
    "ScriptingEventAction",
    "ScriptingEventCondition",
    "EventLink",
    "ScriptingEventSheet",
    "EventVariable",
    "EventLinkType",
    "OperatorType",
    "VariableScope",
    "get_engine_event_scripting",
    # engine_gpu_batch_rendering
    "BatchType",
    "GPUBlendMode",
    "CullMode",
    "EngineGPUBatchRendering",
    "GPUProfile",
    "LODLevel",
    "RenderBatch",
    "SortOrder",
    "SpriteInstance",
    "SpriteLayerConfig",
    "TileLayerConfig",
    "get_gpu_batch_rendering",
    # engine_audio_spatial
    "AudioListener",
    "AudioOcclusion",
    "AudioReverbZone",
    "SpatialAudioSource",
    "AudioSourceType",
    "EngineAudioSpatial",
    "SpatialFilterType",
    "PlaybackState",
    "ProceduralSound",
    "ReverbPreset",
    "RolloffMode",
    "SpatialWaveformType",
    "get_audio_spatial",
    # engine_behavior_orchestrator
    "BehaviorContext",
    "BehaviorNode",
    "BehaviorResult",
    "BehaviorTransition",
    "BehaviorTree",
    "EngineBehaviorOrchestrator",
    "BehaviorNodeType",
    "BehaviorTransitionType",
    "get_engine_behavior_orchestrator",
    # engine_procedural_world
    "BiomeType",
    "DungeonStyle",
    "EngineProceduralWorld",
    "GeneratedDungeon",
    "GeneratedStructure",
    "GeneratedWorld",
    "WorldGenerationAlgorithm",
    "SettlementType",
    "TerrainType",
    "WorldConfig",
    "WorldTile",
    "get_procedural_world",
    # engine_render_pipeline
    "PipelineBlendMode",
    "CullingMode",
    "FrameSnapshot",
    "PostEffect",
    "PostEffectKind",
    "QualityTier",
    "RenderPass",
    "RenderPassType",
    "RenderPipeline",
    "get_render_pipeline",
    # engine_ai_system
    "GameAISystem",
    "NavMeshGenerator",
    "NavMeshAreaType",
    "NavMeshLink",
    "PathfindingEngine",
    "PathfindHeuristic",
    "BehaviorTreeRuntime",
    "BehaviorNodeKind",
    "DecoratorKind",
    "BehaviorResult",
    "AIPerceptionSystem",
    "PerceptionSense",
    "PerceptionEvent",
    "StateMachineAI",
    "AIState",
    "AIStateTransition",
    "get_ai_system",
    # engine_animation_system
    "SystemAnimationClip",
    "SystemAnimationFrame",
    "SystemPlayMode",
    "EasingFunction",
    "EngineAnimationSystem",
    "InterpolationMode",
    "KeyframeSequence",
    "SequenceKeyframe",
    "TweenDefinition",
    "get_animation_system",
    # engine_scene_manager
    "EasingType",
    "EngineSceneManager",
    "SceneDefinition",
    "SceneLayer",
    "ManagerSceneTransition",
    "SceneType",
    "SceneTransitionType",
    "get_scene_manager",
    # engine_navigation_system
    "EngineNavigationSystem",
    "NavLinkType",
    "NavigationAgent",
    "NavigationLink",
    "NavigationMesh",
    "NavigationPath",
    "NavigationState",
    "PathStatus",
    "get_navigation_system",
    # engine_visual_scripting
    "ConnectionType",
    "EngineVisualScripting",
    "ExecutionContext",
    "VisualExecutionMode",
    "ImplementationType",
    "NodeCategory",
    "VisualScriptConnection",
    "NodePort",
    "NodeTemplate",
    "PortDataType",
    "PortDirection",
    "VisualScriptGraph",
    "VisualScriptNode",
    "ScriptVariable",
    "get_engine_visual_scripting",
    # engine_entity_component_system
    "ECSComponent",
    "ComponentBlueprint",
    "ComponentCategory",
    "ComponentUpdatePhase",
    "EngineEntityComponentSystem",
    "ECSEntity",
    "EntityArchetype",
    "ECSSystem",
    "SystemExecutionOrder",
    "ECSWorld",
    "get_entity_component_system",
    # engine_tilemap_runtime
    "AutoTileConfig",
    "EngineTileMapRuntime",
    "RenderOrder",
    "TileAnimationMode",
    "TileBrush",
    "TileCollisionShape",
    "TileDefinition",
    "TileLayer",
    "TileLayerType",
    "TileMap",
    "Tileset",
    "get_tilemap_runtime",
    # engine_progressive_loading
    "ProgressiveChunkState",
    "EngineProgressiveLoading",
    "LoadingQueue",
    "LODTransition",
    "PriorityLevel",
    "ProgressiveStreamingConfig",
    "StreamingPreset",
    "ProgressiveWorldChunk",
    "get_progressive_loading",
    # engine_adaptive_content
    "AdaptiveDifficulty",
    "ContentProfile",
    "ContentType",
    "ContentVariant",
    "DifficultyTier",
    "EngineAdaptiveContent",
    "PlayerArchetype",
    "get_adaptive_content_engine",
    # engine_procedural_dungeon
    "DungeonCorridor",
    "DungeonLayout",
    "DungeonRoom",
    "DungeonTheme",
    "DungeonThemeCategory",
    "EncounterNode",
    "EncounterType",
    "EngineProceduralDungeon",
    "DungeonGenerationAlgorithm",
    "RoomType",
    "TreasureCategory",
    "TreasureNode",
    "get_procedural_dungeon_generator",
    # engine_biome_generation
    "BiomeDefinition",
    "BiomeGenerationPipeline",
    "ClimateBand",
    "BiomeClimateZone",
    "FloraDensity",
    "FloraTemplate",
    "SoilType",
    "TerrainCategory",
    "TerrainLayer",
    "WorldConfiguration",
    "get_biome_generation_pipeline",
    # engine_game_state_analyzer
    "AnalysisDomain",
    "BottleneckSeverity",
    "EntityRelationship",
    "AnalyzerEntityType",
    "GameStateAnalyzer",
    "RelationshipType",
    "SceneSnapshot",
    "SceneStateCategory",
    "SystemicInteraction",
    "get_game_state_analyzer",
    # engine_visual_script_runtime
    "ScriptRuntimeConnection",
    "NodeParameter",
    "VisualScriptNodeType",
    "ParameterType",
    "ScriptRuntimeGraph",
    "ScriptRuntimeNode",
    "TargetLanguage",
    "ValidationIssue",
    "ValidationResult",
    "VisualScriptRuntime",
    "get_visual_script_runtime",
    # engine_texture_atlas
    "AtlasFormat",
    "AtlasPage",
    "AtlasResizePolicy",
    "PackingAlgorithm",
    "PackResult",
    "SpriteOrigin",
    "SpriteRegion",
    "AtlasTextureAtlas",
    "get_texture_atlas",
    # engine_extension_registry
    "BehaviorModule",
    "CompatibilityLevel",
    "ExtensionDefinition",
    "ExtensionDependency",
    "ExtensionRegistry",
    "ExtensionStatus",
    "ExtensionType",
    "ExtensionVersion",
    "InstallSource",
    "ObjectTypeModule",
    "get_extension_registry",
    # Node Editor
    "NodeEditorEngine",
    "NodeCategory",
    "PortDirection",
    "PortDataType",
    "GraphExecutionState",
    "NodePort",
    "NodeConnection",
    "GraphNode",
    "NodeGraph",
    "NodeTemplate",
    "get_node_editor_engine",
    # Scene Serializer
    "SceneSerializerEngine",
    "SerializationFormat",
    "SceneVersion",
    "DiffOperation",
    "MergeStrategy",
    "SceneData",
    "SceneDiff",
    "SceneSavePoint",
    "get_scene_serializer_engine",
    # Engine Signal Bus
    "SignalBus",
    "SignalCategory",
    "ConnectionState",
    "SignalDefinition",
    "SignalConnection",
    "SignalEmission",
    "get_engine_signal_bus",
    # Ecosystem Dynamics
    "EcosystemDynamicsEngine",
    "SpeciesType",
    "PopulationStatus",
    "MigrationTrigger",
    "SeasonType",
    "SpeciesProfile",
    "PopulationSnapshot",
    "RegionEcosystem",
    "MigrationEvent",
    "EcosystemReport",
    "get_ecosystem_dynamics",
    # Civilization Evolution
    "CivilizationEvolutionEngine",
    "TechEra",
    "GovernmentType",
    "RelationStatus",
    "CulturalAspect",
    "TechnologyNode",
    "CulturalIdentity",
    "CivilizationState",
    "DiplomaticEvent",
    "CivilizationSnapshot",
    "get_civilization_engine",
    # Procedural City
    "ProceduralCityEngine",
    "DistrictType",
    "RoadType",
    "BuildingType",
    "CityStyle",
    "RoadSegment",
    "Building",
    "District",
    "CityLayout",
    "CityGenerationConfig",
    "get_procedural_city_engine",
    # Flow State Monitor
    "FlowStateMonitorEngine",
    "FlowState",
    "ChallengeLevel",
    "SkillLevel",
    "SignalType",
    "PlayerSignal",
    "FlowReading",
    "FlowHistory",
    "AdaptationSuggestion",
    "FlowProfile",
    "get_flow_state_monitor",
    "PhysicsEngine",
    "BodyType",
    "CollisionShape",
    "ConstraintType",
    "Vector2D",
    "PhysicsBody",
    "CollisionEvent",
    "PhysicsConstraint",
    "get_physics_engine",
    "BehaviorEngine",
    "BTStatus",
    "FSMStateType",
    "BehaviorType",
    "BTCondition",
    "BTAction",
    "BTNode",
    "BehaviorTree",
    "FSMTransition",
    "FSMState",
    "StateMachine",
    "UtilityAction",
    "UtilityAI",
    "get_behavior_engine",
    "InputEngine",
    "InputDeviceType",
    "InputEventType",
    "GestureType",
    "ActionTriggerType",
    "InputEvent",
    "InputAction",
    "GestureEvent",
    "InputState",
    "get_input_engine",
    "SceneLifecycleEngine",
    "SceneStatus",
    "SceneLayer",
    "TransitionType",
    "NodeType",
    "LifecycleHook",
    "SceneNode",
    "Scene",
    "SceneTransition",
    "get_scene_lifecycle_engine",
    "JobSystemEngine",
    "JobStatus",
    "JobType",
    "WorkerStatus",
    "SchedulingPolicy",
    "Job",
    "JobQueue",
    "JobResult",
    "WorkerThread",
    "JobGraph",
    "get_job_system",
    "ClothPhysicsEngine",
    "ClothSolverType",
    "SoftBodyType",
    "ClothConstraintType",
    "ClothParticle",
    "ClothConstraint",
    "ClothMesh",
    "ClothMaterial",
    "SoftBody",
    "ClothCollisionSphere",
    "get_cloth_physics",
    "LightmappingEngine",
    "BakeStatus",
    "LightType",
    "BakeQuality",
    "GIAlgorithm",
    "LightmapAtlas",
    "LightmapRegion",
    "LightProbe",
    "LightProbeVolume",
    "BakedLight",
    "BakeSettings",
    "BakedScene",
    "get_lightmapping",
    # Spatial Partition
    "SpatialPartitionEngine",
    "PartitionType",
    "QueryType",
    "BoundingBox",
    "SpatialEntry",
    "TreeNode",
    "QueryResult",
    "get_spatial_partition",
    # Inverse Kinematics
    "InverseKinematicsEngine",
    "IKSolverType",
    "JointType",
    "IKConstraintType",
    "IKJoint",
    "IKBoneChain",
    "IKEffector",
    "IKSolution",
    "get_inverse_kinematics",
    # Save System
    "SaveSystemEngine",
    "SaveFormat",
    "SaveSlotType",
    "SaveStatus",
    "SaveMetadata",
    "SaveData",
    "SaveSlot",
    "get_save_system",
    # Event System
    "EventSystemEngine",
    "EventPriority",
    "EventChannel",
    "DispatchMode",
    "GameEvent",
    "EventListener",
    "EventRecord",
    "get_event_system",
    # Fluid Simulation
    "FluidSimulationEngine",
    "FluidSolverType",
    "BoundaryType",
    "FluidDomain",
    "FluidGrid",
    "FluidParticle",
    "FluidSource",
    "FluidObstacle",
    "get_fluid_simulation",
    # Post Processing
    "PostProcessingEngine",
    "EffectType",
    "PPBlendMode",
    "QualityLevel",
    "PipelineStage",
    "PostProcessEffect",
    "EffectParameter",
    "PipelineConfig",
    "EffectResult",
    "get_post_processing",
    # UI System
    "UISystemEngine",
    "WidgetType",
    "LayoutType",
    "AnchorPoint",
    "UIEventType",
    "ThemeMode",
    "UIRect",
    "UIColor",
    "UITheme",
    "UIWidget",
    "UICanvas",
    "UIEvent",
    "UIState",
    "get_ui_system",
    # Network Sync
    "NetworkSyncEngine",
    "SyncAuthority",
    "SyncStrategy",
    "ConnectionState",
    "SyncChannel",
    "MessagePriority",
    "NetworkEntity",
    "SyncMessage",
    "ConnectionInfo",
    "SyncSnapshot",
    "SyncSession",
    "get_network_sync",
    # Performance Monitor
    "PerformanceMonitorEngine",
    "MonitorDomain",
    "AlertCondition",
    "MonitorState",
    "ProfilerMode",
    "MonitorSample",
    "MonitorAlert",
    "ProfileSession",
    "FrameReport",
    "get_performance_monitor",
    # Entity Component Engine
    "EntityComponentEngine",
    "EntityComponentBase",
    "EntityComponentEntity",
    "EntityComponentSystem",
    "ComponentManager",
    "SystemManager",
    "SystemExecutionPhase",
    "EntityComponentState",
    "QueryResult",
    "ComponentStorageType",
    "get_entity_component_engine",
    # Spatial Audio Engine
    "SpatialAudioEngine",
    "AudioSource3D",
    "SpatialAudioListener",
    "AudioOcclusionModel",
    "SpatialAudioReverbZone",
    "DopplerEffect",
    "AudioMixer",
    "AudioChannel",
    "AudioSourceShape",
    "SpatialRolloffMode",
    "SpatialReverbPreset",
    "MixerBusType",
    "OcclusionMethod",
    "get_spatial_audio_engine",
    # Level Streaming Engine
    "LevelStreamingEngine",
    "StreamingCell",
    "CellLoader",
    "LODController",
    "StreamingPriorityQueue",
    "PreloadPredictor",
    "StreamingCellState",
    "StreamingDetailLevel",
    "StreamingLoadPriority",
    "StreamingEngineStrategy",
    "PreloadDirection",
    "get_level_streaming_engine",
    # Dynamic Weather Engine
    "DynamicWeatherEngine",
    "WeatherProfile",
    "WeatherTransition",
    "WeatherZone",
    "WeatherParticleSystem",
    "WeatherParticle",
    "AtmosphereSimulator",
    "DynamicWeatherType",
    "PrecipitationType",
    "TransitionCurve",
    "ScatteringModel",
    "CloudType",
    "get_dynamic_weather_engine",
    # Procedural Terrain Engine
    "ProceduralTerrainEngine",
    "NoiseGenerator",
    "HeightmapGenerator",
    "ErosionSimulator",
    "BiomeMapper",
    "TerrainMeshBuilder",
    "ProceduralTerrainChunk",
    "NoiseType",
    "TerrainLOD",
    "ErosionMode",
    "ProceduralBiomeType",
    "ProceduralChunkState",
    "get_procedural_terrain_engine",
    # Destruction Physics Engine
    "DestructionPhysicsEngine",
    "FracturePattern",
    "VoronoiFracture",
    "DestructionPhysics",
    "StructuralIntegrity",
    "DebrisPool",
    "FractureStyle",
    "MaterialStrength",
    "DebrisState",
    "StructureType",
    "CollapseMode",
    "get_destruction_physics_engine",
    # engine_behavior_composer
    "BehaviorComposerEngine",
    "BehaviorTemplate",
    "BehaviorInstance",
    "BehaviorComposition",
    "BehaviorCategory",
    "BehaviorPriority",
    "BehaviorLifecycle",
    "CompositionMode",
    "get_behavior_composer",
    # engine_asset_compiler
    "AssetCompilerEngine",
    "AssetType",
    "AssetFormat",
    "AssetSource",
    "CompileResult",
    "AssetBundle",
    "CompileConfig",
    "CompileStatus",
    "CompressionLevel",
    "BundleStrategy",
    "get_asset_compiler",
    # engine_unified_runtime
    "UnifiedGameRuntime",
    "RuntimeState",
    "TimestepMode",
    "SceneState",
    "RenderPhase",
    "PhysicsStep",
    "AudioChannel",
    "InputLayer",
    "FrameTiming",
    "SceneInstance",
    "RenderStats",
    "PhysicsStats",
    "AudioStats",
    "RuntimeProfile",
    "GameLoopOrchestrator",
    "SceneLifecycleManager",
    "PhysicsCoordinator",
    "RenderPipelineManager",
    "AudioMixer",
    "InputAggregator",
    "EntityCoordinator",
    "PerformanceProfiler",
    "get_unified_runtime",
    # engine_adaptive_rendering
    "AdaptiveRenderingEngine",
    "QualityTier",
    "RenderFeature",
    "AdaptationStrategy",
    "PerformanceMetrics",
    "QualityPreset",
    "AdaptationEvent",
    "MetricsCollector",
    "QualityManager",
    "get_adaptive_rendering",
    # engine_physics_optimizer
    "PhysicsOptimizerEngine",
    "PhysicsSolverType",
    "SpatialStrategy",
    "OptimizationTarget",
    "PhysicsQualityLevel",
    "PhysicsProfile",
    "PhysicsConfiguration",
    "OptimizationRecommendation",
    "SpatialOptimizer",
    "SolverOptimizer",
    "get_physics_optimizer",
    # engine_ai_native_core
    "AINativeEngineCore",
    "EngineMode",
    "EngineCommand",
    "EngineEventType",
    "EntityCategory",
    "EngineStateSnapshot",
    "EngineCommandResult",
    "EngineEvent",
    "OptimizationProfile",
    "GameCreationSpec",
    "get_ai_native_engine",
    # Server Registry
    "ServerRegistry",
    "ServerType",
    "ServerStatus",
    "ServerPriority",
    "ServerConfig",
    "ServerInfo",
    "get_engine_server_registry",
    # Scene Tree
    "SceneTree",
    "SceneNode",
    "NodeType",
    "NodeLifecycle",
    "get_scene_tree",
    # Game Component System
    "GameComponentRegistry",
    "ComponentCategory",
    "ComponentLifecycle",
    "ComponentDefinition",
    "ComponentInstance",
    "GameEntity",
    "get_component_registry",
]