"""
SparkLabs Engine - Live Feedback System

A real-time AI analysis system that monitors the game being built and provides
intelligent feedback, suggestions, and optimization recommendations during the
development process for the AI-native game engine.

Architecture:
  LiveFeedbackEngine (singleton)
    |-- FeedbackItem (individual feedback entry with categorization)
    |-- AnalysisSnapshot (time-stamped capture of analysis state)
    |-- FeedbackRule (configurable heuristic rule for detection)
    |-- FeedbackCategory / FeedbackSeverity / AnalysisScope (domain enums)

Core Capabilities:
  - analyze_entity: Per-entity heuristic checks across all categories
  - analyze_scene: Scene-wide analysis for composition and relationships
  - analyze_project: Project-level structural and architectural analysis
  - analyze_runtime: Real-time performance and gameplay metrics analysis
  - analyze_asset: Asset-level resource and quality validation
  - register_rule: Extendable rule system for custom feedback detection
  - apply_fix / dismiss_feedback: Feedback lifecycle management
  - get_feedback_summary: Aggregated overview of all feedback
  - get_stats: Operational statistics for the feedback engine
"""

from __future__ import annotations

import json
import threading
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Callable, Dict, List, Optional, Tuple

_time_module = time


# ---------------------------------------------------------------------------
# Domain Enums
# ---------------------------------------------------------------------------


class FeedbackCategory(Enum):
    PERFORMANCE = "performance"
    VISUAL = "visual"
    GAMEPLAY = "gameplay"
    ACCESSIBILITY = "accessibility"
    UX = "ux"
    CODE = "code"
    ARCHITECTURE = "architecture"
    RESOURCE = "resource"
    OPTIMIZATION = "optimization"
    BALANCE = "balance"


class FeedbackSeverity(Enum):
    SUGGESTION = "suggestion"
    RECOMMENDATION = "recommendation"
    WARNING = "warning"
    ISSUE = "issue"
    CRITICAL = "critical"


class AnalysisScope(Enum):
    ENTITY = "entity"
    SCENE = "scene"
    PROJECT = "project"
    RUNTIME = "runtime"
    ASSET = "asset"


# ---------------------------------------------------------------------------
# Severity Weight Map (for summary prioritization)
# ---------------------------------------------------------------------------

_SEVERITY_WEIGHT: Dict[str, int] = {
    FeedbackSeverity.SUGGESTION.value: 1,
    FeedbackSeverity.RECOMMENDATION.value: 2,
    FeedbackSeverity.WARNING.value: 3,
    FeedbackSeverity.ISSUE.value: 4,
    FeedbackSeverity.CRITICAL.value: 5,
}


# ---------------------------------------------------------------------------
# Dataclasses
# ---------------------------------------------------------------------------


@dataclass
class FeedbackItem:
    """A single piece of feedback generated by the analysis engine."""

    feedback_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    category: FeedbackCategory = FeedbackCategory.PERFORMANCE
    severity: FeedbackSeverity = FeedbackSeverity.SUGGESTION
    scope: AnalysisScope = AnalysisScope.ENTITY
    title: str = ""
    description: str = ""
    suggestion: str = ""
    source_entity: str = ""
    auto_fixable: bool = False
    applied: bool = False
    created_at: float = field(default_factory=_time_module.time)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "feedback_id": self.feedback_id,
            "category": self.category.value,
            "severity": self.severity.value,
            "scope": self.scope.value,
            "title": self.title,
            "description": self.description,
            "suggestion": self.suggestion,
            "source_entity": self.source_entity,
            "auto_fixable": self.auto_fixable,
            "applied": self.applied,
            "created_at": self.created_at,
        }


@dataclass
class AnalysisSnapshot:
    """A time-stamped capture of analysis state and metrics."""

    snapshot_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    scope: AnalysisScope = AnalysisScope.SCENE
    entities_analyzed: int = 0
    metrics: Dict[str, Any] = field(default_factory=dict)
    timestamp: float = field(default_factory=_time_module.time)
    duration_ms: float = 0.0

    def to_dict(self) -> Dict[str, Any]:
        return {
            "snapshot_id": self.snapshot_id,
            "scope": self.scope.value,
            "entities_analyzed": self.entities_analyzed,
            "metrics": self.metrics,
            "timestamp": self.timestamp,
            "duration_ms": self.duration_ms,
        }


@dataclass
class FeedbackRule:
    """A configurable heuristic rule for feedback detection."""

    rule_id: str = field(default_factory=lambda: uuid.uuid4().hex)
    name: str = ""
    category: FeedbackCategory = FeedbackCategory.PERFORMANCE
    condition_template: str = ""
    suggestion_template: str = ""
    enabled: bool = True
    priority: int = 0


# ---------------------------------------------------------------------------
# Built-in Rule Definitions
# ---------------------------------------------------------------------------

_BUILTIN_RULES: List[Dict[str, Any]] = [
    # -- Performance Rules --
    {
        "name": "low_frame_rate",
        "category": FeedbackCategory.PERFORMANCE,
        "condition_template": "fps < 30",
        "suggestion_template": "Target frame rate is below 30 FPS. Consider reducing draw calls, lowering texture resolution, or enabling LOD.",
        "priority": 90,
    },
    {
        "name": "high_draw_calls",
        "category": FeedbackCategory.PERFORMANCE,
        "condition_template": "draw_calls > 500",
        "suggestion_template": "Draw call count ({draw_calls}) exceeds recommended limit. Batch sprites, merge static geometry, or use texture atlases.",
        "priority": 85,
    },
    {
        "name": "high_memory_usage",
        "category": FeedbackCategory.PERFORMANCE,
        "condition_template": "memory_mb > 512",
        "suggestion_template": "Memory usage ({memory_mb} MB) is high. Check for texture leaks, unpooled object allocation, or large audio buffers.",
        "priority": 80,
    },
    {
        "name": "excessive_entities",
        "category": FeedbackCategory.PERFORMANCE,
        "condition_template": "entity_count > 1000",
        "suggestion_template": "Scene contains {entity_count} entities. Consider spatial partitioning, object pooling, or culling inactive entities.",
        "priority": 75,
    },
    {
        "name": "large_texture_dimensions",
        "category": FeedbackCategory.PERFORMANCE,
        "condition_template": "texture_width > 2048 or texture_height > 2048",
        "suggestion_template": "Texture dimensions ({texture_width}x{texture_height}) may impact memory and load times. Use mipmaps and compress where possible.",
        "priority": 65,
    },
    # -- Visual Rules --
    {
        "name": "low_color_contrast",
        "category": FeedbackCategory.VISUAL,
        "condition_template": "contrast_ratio < 3.0",
        "suggestion_template": "Color contrast ratio ({contrast_ratio}) is low. This may reduce readability. Adjust foreground/background colors for better distinction.",
        "priority": 70,
    },
    {
        "name": "z_order_conflict",
        "category": FeedbackCategory.VISUAL,
        "condition_template": "z_conflicts > 0",
        "suggestion_template": "{z_conflicts} z-ordering conflicts detected. Ensure consistent depth layering to prevent visual flickering.",
        "priority": 75,
    },
    {
        "name": "missing_texture_reference",
        "category": FeedbackCategory.VISUAL,
        "condition_template": "missing_textures > 0",
        "suggestion_template": "{missing_textures} texture references are missing or unresolved. Assign fallback textures or import missing assets.",
        "priority": 90,
    },
    {
        "name": "overlapping_ui_elements",
        "category": FeedbackCategory.VISUAL,
        "condition_template": "ui_overlaps > 0",
        "suggestion_template": "{ui_overlaps} UI elements overlap. Review layout constraints and anchor positions to prevent occlusion.",
        "priority": 60,
    },
    # -- Gameplay Rules --
    {
        "name": "steep_difficulty_curve",
        "category": FeedbackCategory.GAMEPLAY,
        "condition_template": "difficulty_slope > 1.5",
        "suggestion_template": "Difficulty curve slope ({difficulty_slope}) is steep. Gradual progression improves player retention and reduces frustration.",
        "priority": 80,
    },
    {
        "name": "high_spawn_rate",
        "category": FeedbackCategory.GAMEPLAY,
        "condition_template": "spawns_per_minute > 60",
        "suggestion_template": "Spawn rate ({spawns_per_minute}/min) may overwhelm players. Cap concurrent enemies or introduce spawn cooldowns.",
        "priority": 75,
    },
    {
        "name": "low_reward_frequency",
        "category": FeedbackCategory.GAMEPLAY,
        "condition_template": "rewards_per_minute < 0.5",
        "suggestion_template": "Reward frequency ({rewards_per_minute}/min) is low. Increase collectible density or add intermediate reward milestones.",
        "priority": 70,
    },
    {
        "name": "insufficient_player_feedback",
        "category": FeedbackCategory.GAMEPLAY,
        "condition_template": "feedback_events_per_action < 0.3",
        "suggestion_template": "Player actions lack sufficient feedback ({feedback_events_per_action} events/action). Add visual effects, sounds, or haptic responses.",
        "priority": 68,
    },
    # -- Accessibility Rules --
    {
        "name": "small_font_size",
        "category": FeedbackCategory.ACCESSIBILITY,
        "condition_template": "min_font_size < 12",
        "suggestion_template": "Minimum font size ({min_font_size}px) is small. Provide scalable text options or increase default size to at least 14px.",
        "priority": 80,
    },
    {
        "name": "color_only_cues",
        "category": FeedbackCategory.ACCESSIBILITY,
        "condition_template": "color_only_indicators > 0",
        "suggestion_template": "{color_only_indicators} game elements rely solely on color for information. Add icons, patterns, or text labels for color-blind accessibility.",
        "priority": 85,
    },
    {
        "name": "missing_control_options",
        "category": FeedbackCategory.ACCESSIBILITY,
        "condition_template": "remappable_controls < 5",
        "suggestion_template": "Only {remappable_controls} controls are remappable. Offer full control remapping and alternative input schemes.",
        "priority": 75,
    },
    {
        "name": "missing_audio_cues",
        "category": FeedbackCategory.ACCESSIBILITY,
        "condition_template": "audio_cue_coverage < 0.6",
        "suggestion_template": "Audio cue coverage ({audio_cue_coverage}) is below threshold. Add subtitles, visual indicators, or vibration for critical events.",
        "priority": 70,
    },
    # -- UX Rules --
    {
        "name": "deep_menu_nesting",
        "category": FeedbackCategory.UX,
        "condition_template": "menu_depth > 3",
        "suggestion_template": "Menu navigation depth ({menu_depth}) may frustrate users. Flatten menus or add shortcuts for frequent actions.",
        "priority": 60,
    },
    {
        "name": "inconsistent_input_mapping",
        "category": FeedbackCategory.UX,
        "condition_template": "input_consistency < 0.7",
        "suggestion_template": "Input mapping consistency ({input_consistency}) is low. Unify similar actions across contexts to reduce cognitive load.",
        "priority": 55,
    },
    # -- Code Rules --
    {
        "name": "unconnected_event",
        "category": FeedbackCategory.CODE,
        "condition_template": "unconnected_events > 0",
        "suggestion_template": "{unconnected_events} events have no listeners connected. Remove unused events or wire up intended handlers.",
        "priority": 80,
    },
    {
        "name": "missing_entity_reference",
        "category": FeedbackCategory.CODE,
        "condition_template": "missing_references > 0",
        "suggestion_template": "{missing_references} entity references are dangling or unresolved. Verify target entities exist and are correctly named.",
        "priority": 85,
    },
    {
        "name": "circular_dependency",
        "category": FeedbackCategory.CODE,
        "condition_template": "circular_deps > 0",
        "suggestion_template": "{circular_deps} circular dependencies detected. Refactor into a shared interface or utility module to break cycles.",
        "priority": 90,
    },
    # -- Architecture Rules --
    {
        "name": "scene_too_complex",
        "category": FeedbackCategory.ARCHITECTURE,
        "condition_template": "scene_depth > 10",
        "suggestion_template": "Scene hierarchy depth ({scene_depth}) is deep. Flatten the hierarchy or split into sub-scenes for maintainability.",
        "priority": 70,
    },
    {
        "name": "flat_hierarchy_warning",
        "category": FeedbackCategory.ARCHITECTURE,
        "condition_template": "entity_hierarchy_depth < 1.5",
        "suggestion_template": "Entity hierarchy is nearly flat (avg depth {entity_hierarchy_depth}). Group related entities under logical parent nodes.",
        "priority": 40,
    },
    {
        "name": "high_component_coupling",
        "category": FeedbackCategory.ARCHITECTURE,
        "condition_template": "component_coupling > 0.8",
        "suggestion_template": "Component coupling ({component_coupling}) is high. Introduce event-driven communication or dependency injection to reduce tight coupling.",
        "priority": 75,
    },
    # -- Resource Rules --
    {
        "name": "large_asset_bundle",
        "category": FeedbackCategory.RESOURCE,
        "condition_template": "bundle_size_mb > 100",
        "suggestion_template": "Asset bundle size ({bundle_size_mb} MB) is large. Compress textures, strip unused assets, and use streaming where possible.",
        "priority": 70,
    },
    {
        "name": "duplicate_assets",
        "category": FeedbackCategory.RESOURCE,
        "condition_template": "duplicate_count > 0",
        "suggestion_template": "{duplicate_count} duplicate assets found. De-duplicate to reduce bundle size and simplify asset management.",
        "priority": 65,
    },
    # -- Optimization Rules --
    {
        "name": "unbatched_sprites",
        "category": FeedbackCategory.OPTIMIZATION,
        "condition_template": "unbatched_count > 50",
        "suggestion_template": "{unbatched_count} sprites are not batched. Use sprite atlases and share materials to reduce draw calls.",
        "priority": 80,
    },
    {
        "name": "underutilized_object_pool",
        "category": FeedbackCategory.OPTIMIZATION,
        "condition_template": "pool_hit_ratio < 0.5",
        "suggestion_template": "Object pool hit ratio ({pool_hit_ratio}) is low. Increase pool sizes or adjust pre-warming for frequently spawned objects.",
        "priority": 65,
    },
    # -- Balance Rules --
    {
        "name": "stat_imbalance",
        "category": FeedbackCategory.BALANCE,
        "condition_template": "stat_variance > 0.5",
        "suggestion_template": "Entity stat variance ({stat_variance}) is high. Review damage, health, and speed values for competitive fairness.",
        "priority": 75,
    },
    {
        "name": "economy_inflation_risk",
        "category": FeedbackCategory.BALANCE,
        "condition_template": "currency_inflow_ratio > 3.0",
        "suggestion_template": "Currency inflow to outflow ratio ({currency_inflow_ratio}) suggests inflation risk. Adjust pricing or reduce reward frequency.",
        "priority": 70,
    },
]


# ---------------------------------------------------------------------------
# Heuristic Threshold Constants
# ---------------------------------------------------------------------------

_FPS_WARNING_THRESHOLD = 30
_FPS_CRITICAL_THRESHOLD = 15
_DRAW_CALL_WARNING = 500
_DRAW_CALL_CRITICAL = 1000
_MEMORY_WARNING_MB = 512
_MEMORY_CRITICAL_MB = 1024
_ENTITY_COUNT_WARNING = 1000
_ENTITY_COUNT_CRITICAL = 3000
_TEXTURE_DIM_WARNING = 2048
_TEXTURE_DIM_CRITICAL = 4096
_CONTRAST_RATIO_MIN = 3.0
_FONT_SIZE_MIN = 12
_MENU_DEPTH_MAX = 3
_SCENE_DEPTH_MAX = 10


# ---------------------------------------------------------------------------
# Live Feedback Engine (Singleton)
# ---------------------------------------------------------------------------


class LiveFeedbackEngine:
    """
    Real-time AI analysis engine that monitors the game being built and
    provides intelligent feedback, suggestions, and optimization
    recommendations during the development process.

    Usage:
        engine = LiveFeedbackEngine.get_instance()
        items = engine.analyze_entity("player_01", entity_data)
        summary = engine.get_feedback_summary()
    """

    _instance: Optional["LiveFeedbackEngine"] = None
    _lock: threading.RLock = threading.RLock()

    def __new__(cls) -> "LiveFeedbackEngine":
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    instance = super().__new__(cls)
                    instance._initialized = False
                    cls._instance = instance
        return cls._instance

    @classmethod
    def get_instance(cls) -> "LiveFeedbackEngine":
        if cls._instance is None:
            cls()
        return cls._instance

    def __init__(self) -> None:
        if self._initialized:
            return
        self._initialized = True

        self._feedback_items: Dict[str, FeedbackItem] = {}
        self._feedback_index: Dict[str, List[str]] = {}
        self._rules: Dict[str, FeedbackRule] = {}
        self._snapshots: deque = deque(maxlen=100)
        self._dismissed_ids: set = set()

        self._total_analyses: int = 0
        self._total_feedback_generated: int = 0
        self._total_fixes_applied: int = 0
        self._last_analysis_time: float = 0.0

        self._initialize_builtin_rules()

    # ------------------------------------------------------------------
    # Rule Management
    # ------------------------------------------------------------------

    def _initialize_builtin_rules(self) -> None:
        for rule_def in _BUILTIN_RULES:
            self.register_rule(
                name=rule_def["name"],
                category=rule_def["category"],
                condition_template=rule_def["condition_template"],
                suggestion_template=rule_def["suggestion_template"],
                priority=rule_def["priority"],
            )

    def register_rule(
        self,
        name: str,
        category: FeedbackCategory,
        condition_template: str,
        suggestion_template: str,
        priority: int = 0,
    ) -> FeedbackRule:
        with self._lock:
            rule = FeedbackRule(
                name=name,
                category=category,
                condition_template=condition_template,
                suggestion_template=suggestion_template,
                priority=priority,
            )
            self._rules[rule.rule_id] = rule
            return rule

    def get_rules(
        self,
        category: Optional[FeedbackCategory] = None,
        enabled_only: bool = True,
    ) -> List[FeedbackRule]:
        with self._lock:
            result = list(self._rules.values())
            if category is not None:
                result = [r for r in result if r.category == category]
            if enabled_only:
                result = [r for r in result if r.enabled]
            result.sort(key=lambda r: r.priority, reverse=True)
            return result

    # ------------------------------------------------------------------
    # Analysis Methods
    # ------------------------------------------------------------------

    def analyze_entity(
        self, entity_id: str, entity_data: Dict[str, Any]
    ) -> List[FeedbackItem]:
        """
        Run heuristic checks on a single entity across all relevant
        categories: performance, visual, gameplay, accessibility, code.
        """
        start = _time_module.time()
        items: List[FeedbackItem] = []

        self._check_entity_performance(entity_id, entity_data, items)
        self._check_entity_visual(entity_id, entity_data, items)
        self._check_entity_gameplay(entity_id, entity_data, items)
        self._check_entity_accessibility(entity_id, entity_data, items)
        self._check_entity_code(entity_id, entity_data, items)

        duration_ms = (_time_module.time() - start) * 1000.0
        self._record_analysis(AnalysisScope.ENTITY, 1, entity_data, duration_ms, items)
        return items

    def analyze_scene(
        self, scene_id: str, scene_data: Dict[str, Any]
    ) -> List[FeedbackItem]:
        """
        Run heuristic checks on an entire scene: entity composition,
        spatial relationships, z-ordering, and overall complexity.
        """
        start = _time_module.time()
        items: List[FeedbackItem] = []

        entity_count = scene_data.get("entity_count", 0)
        entities = scene_data.get("entities", [])

        # Performance: entity count
        if entity_count > _ENTITY_COUNT_CRITICAL:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.SCENE, "Excessive Scene Entities",
                f"Scene contains {entity_count} entities, far above the recommended maximum.",
                "Split the scene into multiple sub-scenes. Use spatial partitioning and object pooling.",
                scene_id,
            ))
        elif entity_count > _ENTITY_COUNT_WARNING:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.SCENE, "High Entity Count",
                f"Scene has {entity_count} entities. Performance may degrade on lower-end devices.",
                "Consider object pooling, LOD culling, or reducing decorative entities.",
                scene_id,
            ))

        # Z-ordering conflicts
        z_conflicts = scene_data.get("z_conflicts", 0)
        if z_conflicts > 0:
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.WARNING,
                AnalysisScope.SCENE, "Z-Ordering Conflicts Detected",
                f"{z_conflicts} entities share overlapping z-positions causing rendering ambiguity.",
                "Assign distinct z-values or use explicit sorting layers.",
                scene_id,
            ))

        # Architecture: scene depth
        scene_depth = scene_data.get("scene_depth", 0)
        if scene_depth > _SCENE_DEPTH_MAX:
            items.append(self._make_feedback(
                FeedbackCategory.ARCHITECTURE, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.SCENE, "Deep Scene Hierarchy",
                f"Scene hierarchy depth is {scene_depth}, which complicates traversal.",
                "Flatten the entity tree or split logical groups into prefabs.",
                scene_id,
            ))

        # Visual: missing textures across entities
        missing_tex = scene_data.get("missing_texture_count", 0)
        if missing_tex > 0:
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.ISSUE,
                AnalysisScope.SCENE, "Missing Texture References",
                f"{missing_tex} texture references are unresolved in this scene.",
                "Import missing assets or assign default placeholder textures.",
                scene_id,
                auto_fixable=missing_tex <= 5,
            ))

        # Visual: overlapping UI
        ui_overlaps = scene_data.get("ui_overlaps", 0)
        if ui_overlaps > 0:
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.SUGGESTION,
                AnalysisScope.SCENE, "Overlapping UI Elements",
                f"{ui_overlaps} UI elements overlap and may be obscured.",
                "Review anchor points and layout constraints.",
                scene_id,
            ))

        # Code: unconnected events
        unconnected = scene_data.get("unconnected_events", 0)
        if unconnected > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.WARNING,
                AnalysisScope.SCENE, "Unconnected Events",
                f"{unconnected} events are fired but have no listeners.",
                "Wire up handlers or remove dead event dispatches.",
                scene_id,
            ))

        # Code: circular dependencies
        circular = scene_data.get("circular_dependencies", 0)
        if circular > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.CRITICAL,
                AnalysisScope.SCENE, "Circular Dependencies",
                f"{circular} circular dependency chains detected among scene entities.",
                "Break cycles by introducing shared interfaces or mediator patterns.",
                scene_id,
            ))

        # Architecture: component coupling
        coupling = scene_data.get("component_coupling", 0.0)
        if coupling > 0.8:
            items.append(self._make_feedback(
                FeedbackCategory.ARCHITECTURE, FeedbackSeverity.WARNING,
                AnalysisScope.SCENE, "High Component Coupling",
                f"Component coupling score is {coupling:.2f}.",
                "Decouple with event buses or dependency injection.",
                scene_id,
            ))

        # Architecture: hierarchy depth average
        avg_depth = scene_data.get("avg_hierarchy_depth", 0.0)
        if avg_depth < 1.5 and entity_count > 10:
            items.append(self._make_feedback(
                FeedbackCategory.ARCHITECTURE, FeedbackSeverity.SUGGESTION,
                AnalysisScope.SCENE, "Flat Entity Hierarchy",
                f"Average hierarchy depth is {avg_depth:.1f} with {entity_count} entities.",
                "Group related entities under logical parent containers.",
                scene_id,
            ))

        # Resource: duplicate assets
        duplicates = scene_data.get("duplicate_assets", 0)
        if duplicates > 0:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.SCENE, "Duplicate Assets",
                f"{duplicates} duplicate asset instances found.",
                "De-duplicate assets and use shared references to save memory.",
                scene_id,
                auto_fixable=duplicates <= 10,
            ))

        duration_ms = (_time_module.time() - start) * 1000.0
        self._record_analysis(
            AnalysisScope.SCENE, entity_count, scene_data, duration_ms, items,
        )
        return items

    def analyze_project(
        self, project_data: Dict[str, Any]
    ) -> List[FeedbackItem]:
        """
        Run heuristic checks at the project level: overall architecture,
        resource bundling, global settings, and cross-scene concerns.
        """
        start = _time_module.time()
        items: List[FeedbackItem] = []
        project_id = project_data.get("project_id", "project")

        # Resource: bundle size
        bundle_mb = project_data.get("bundle_size_mb", 0)
        if bundle_mb > 200:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.PROJECT, "Excessive Bundle Size",
                f"Total bundle size is {bundle_mb} MB, which impacts download and load times.",
                "Compress textures, strip unused assets, and enable streaming for large levels.",
                project_id,
            ))
        elif bundle_mb > 100:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.WARNING,
                AnalysisScope.PROJECT, "Large Bundle Size",
                f"Bundle size ({bundle_mb} MB) is approaching recommended limits.",
                "Audit assets for compression opportunities and unused files.",
                project_id,
            ))

        # Architecture: scene count and organization
        scene_count = project_data.get("scene_count", 0)
        if scene_count > 50:
            items.append(self._make_feedback(
                FeedbackCategory.ARCHITECTURE, FeedbackSeverity.WARNING,
                AnalysisScope.PROJECT, "High Scene Count",
                f"Project contains {scene_count} scenes. Navigation and loading may become complex.",
                "Group related scenes into level packs and consider scene streaming.",
                project_id,
            ))

        # Code: global event connections
        global_events_unconnected = project_data.get("global_unconnected_events", 0)
        if global_events_unconnected > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.ISSUE,
                AnalysisScope.PROJECT, "Unconnected Global Events",
                f"{global_events_unconnected} global events have no listeners across all scenes.",
                "Clean up unused global events or connect intended handlers.",
                project_id,
            ))

        # Code: missing cross-scene references
        missing_refs = project_data.get("missing_cross_scene_refs", 0)
        if missing_refs > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.ISSUE,
                AnalysisScope.PROJECT, "Dangling Cross-Scene References",
                f"{missing_refs} references point to entities in unloaded or deleted scenes.",
                "Use persistent ID systems or lazy-load referenced entities.",
                project_id,
            ))

        # Optimization: global settings
        if not project_data.get("object_pooling_enabled", False):
            items.append(self._make_feedback(
                FeedbackCategory.OPTIMIZATION, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.PROJECT, "Object Pooling Not Enabled",
                "Global object pooling is disabled. Frequent allocations cause GC pressure.",
                "Enable object pooling for frequently spawned entities (bullets, particles, etc.).",
                project_id,
            ))

        if not project_data.get("texture_atlas_enabled", False):
            items.append(self._make_feedback(
                FeedbackCategory.OPTIMIZATION, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.PROJECT, "Texture Atlas Not Configured",
                "Sprite batching with texture atlases is not enabled.",
                "Configure a shared texture atlas to reduce draw calls.",
                project_id,
            ))

        # Accessibility: project-level settings
        if not project_data.get("color_blind_mode_supported", False):
            items.append(self._make_feedback(
                FeedbackCategory.ACCESSIBILITY, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.PROJECT, "No Color-Blind Support",
                "The project does not include color-blind friendly modes.",
                "Add configurable color palettes or pattern-based indicators.",
                project_id,
            ))

        if not project_data.get("subtitle_support", False):
            items.append(self._make_feedback(
                FeedbackCategory.ACCESSIBILITY, FeedbackSeverity.SUGGESTION,
                AnalysisScope.PROJECT, "No Subtitle System",
                "Subtitles or closed captions are not configured.",
                "Implement a subtitle system for dialogue and important audio cues.",
                project_id,
            ))

        # Balance: global economy if applicable
        economy_data = project_data.get("economy_settings", {})
        if economy_data:
            inflow = economy_data.get("currency_inflow_per_minute", 0.0)
            outflow = economy_data.get("currency_outflow_per_minute", 0.0)
            if outflow > 0 and inflow / outflow > 3.0:
                items.append(self._make_feedback(
                    FeedbackCategory.BALANCE, FeedbackSeverity.WARNING,
                    AnalysisScope.PROJECT, "Economy Inflation Risk",
                    f"Currency inflow ({inflow:.1f}/min) far exceeds outflow ({outflow:.1f}/min).",
                    "Reduce reward amounts or increase pricing for key items.",
                    project_id,
                ))

        duration_ms = (_time_module.time() - start) * 1000.0
        self._record_analysis(
            AnalysisScope.PROJECT, 0, project_data, duration_ms, items,
        )
        return items

    def analyze_runtime(
        self, runtime_metrics: Dict[str, Any]
    ) -> List[FeedbackItem]:
        """
        Analyze live runtime metrics: frame rate, memory, draw calls,
        entity counts, and gameplay flow indicators.
        """
        start = _time_module.time()
        items: List[FeedbackItem] = []
        runtime_id = runtime_metrics.get("session_id", "runtime")

        # Performance: frame rate
        fps = runtime_metrics.get("fps", 60)
        if fps < _FPS_CRITICAL_THRESHOLD:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.RUNTIME, "Critical Frame Rate Drop",
                f"FPS is {fps:.0f}, well below playable threshold.",
                "Immediately reduce draw calls, disable expensive post-effects, enable LOD.",
                runtime_id,
            ))
        elif fps < _FPS_WARNING_THRESHOLD:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.RUNTIME, "Low Frame Rate",
                f"FPS is {fps:.0f}. Player experience may be degraded.",
                "Profile draw calls and shader complexity. Reduce particle counts.",
                runtime_id,
            ))

        # Performance: draw calls
        draw_calls = runtime_metrics.get("draw_calls", 0)
        if draw_calls > _DRAW_CALL_CRITICAL:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.RUNTIME, "Excessive Draw Calls",
                f"Draw calls ({draw_calls}) severely impact GPU performance.",
                "Batch sprites, merge static meshes, reduce unique materials.",
                runtime_id,
            ))
        elif draw_calls > _DRAW_CALL_WARNING:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.RUNTIME, "High Draw Call Count",
                f"Draw calls ({draw_calls}) are approaching performance limits.",
                "Consider GPU instancing and texture atlasing.",
                runtime_id,
            ))

        # Performance: memory
        memory_mb = runtime_metrics.get("memory_usage_mb", 0)
        if memory_mb > _MEMORY_CRITICAL_MB:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.RUNTIME, "Critical Memory Usage",
                f"Memory usage ({memory_mb} MB) risks out-of-memory crashes.",
                "Release unused assets, reduce texture sizes, enable asset streaming.",
                runtime_id,
            ))
        elif memory_mb > _MEMORY_WARNING_MB:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.RUNTIME, "High Memory Usage",
                f"Memory usage ({memory_mb} MB) is elevated.",
                "Check for asset leaks and unpooled object allocations.",
                runtime_id,
            ))

        # Performance: entity count in active scene
        entity_count = runtime_metrics.get("active_entity_count", 0)
        if entity_count > _ENTITY_COUNT_CRITICAL:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.RUNTIME, "Excessive Active Entities",
                f"{entity_count} entities active simultaneously.",
                "Enable frustum culling, deactivate off-screen entities, use LOD groups.",
                runtime_id,
            ))

        # Gameplay: spawn rate
        spawn_rate = runtime_metrics.get("spawns_per_minute", 0)
        if spawn_rate > 60:
            items.append(self._make_feedback(
                FeedbackCategory.GAMEPLAY, FeedbackSeverity.WARNING,
                AnalysisScope.RUNTIME, "High Spawn Rate",
                f"Spawn rate is {spawn_rate:.0f} per minute, potentially overwhelming.",
                "Introduce spawn caps, cooldowns, or wave-based spawning.",
                runtime_id,
            ))

        # Gameplay: reward frequency
        rewards = runtime_metrics.get("rewards_per_minute", 0.0)
        if 0 < rewards < 0.5:
            items.append(self._make_feedback(
                FeedbackCategory.GAMEPLAY, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.RUNTIME, "Low Reward Frequency",
                f"Only {rewards:.2f} rewards per minute. Players need more positive reinforcement.",
                "Add intermediate collectibles or milestone bonuses.",
                runtime_id,
            ))

        # Gameplay: difficulty indicators
        difficulty = runtime_metrics.get("difficulty_slope", 0.0)
        if difficulty > 1.5:
            items.append(self._make_feedback(
                FeedbackCategory.GAMEPLAY, FeedbackSeverity.WARNING,
                AnalysisScope.RUNTIME, "Steep Difficulty Ramp",
                f"Difficulty slope is {difficulty:.2f}. Players may hit a wall.",
                "Smooth the progression curve with gentler stat increases.",
                runtime_id,
            ))

        # Optimization: pool hit ratio
        pool_ratio = runtime_metrics.get("pool_hit_ratio", 1.0)
        if pool_ratio < 0.5:
            items.append(self._make_feedback(
                FeedbackCategory.OPTIMIZATION, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.RUNTIME, "Low Pool Hit Ratio",
                f"Object pool hit ratio is {pool_ratio:.2f}.",
                "Increase pool pre-warm sizes or adjust pool eviction policy.",
                runtime_id,
            ))

        # Optimization: unbatched sprites
        unbatched = runtime_metrics.get("unbatched_sprites", 0)
        if unbatched > 50:
            items.append(self._make_feedback(
                FeedbackCategory.OPTIMIZATION, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.RUNTIME, "Unbatched Sprites",
                f"{unbatched} sprites are rendered without batching.",
                "Consolidate into shared material groups or texture atlases.",
                runtime_id,
            ))

        duration_ms = (_time_module.time() - start) * 1000.0
        self._record_analysis(
            AnalysisScope.RUNTIME, 0, runtime_metrics, duration_ms, items,
        )
        return items

    def analyze_asset(
        self, asset_id: str, asset_data: Dict[str, Any]
    ) -> List[FeedbackItem]:
        """
        Analyze an individual asset for quality, performance, and resource issues.
        Checks texture dimensions, file size, format, and naming conventions.
        """
        start = _time_module.time()
        items: List[FeedbackItem] = []

        asset_type = asset_data.get("type", "unknown")

        # Performance: texture dimensions
        if asset_type in ("texture", "sprite", "image"):
            width = asset_data.get("width", 0)
            height = asset_data.get("height", 0)
            if width > _TEXTURE_DIM_CRITICAL or height > _TEXTURE_DIM_CRITICAL:
                items.append(self._make_feedback(
                    FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                    AnalysisScope.ASSET, "Texture Too Large",
                    f"Texture dimensions ({width}x{height}) exceed recommended maximum.",
                    "Downscale and use mipmaps. Split large textures into tiles if needed.",
                    asset_id,
                ))
            elif width > _TEXTURE_DIM_WARNING or height > _TEXTURE_DIM_WARNING:
                items.append(self._make_feedback(
                    FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                    AnalysisScope.ASSET, "Large Texture Dimensions",
                    f"Texture size ({width}x{height}) may impact performance on mobile.",
                    "Consider providing lower-resolution variants or compressing.",
                    asset_id,
                ))

        # Resource: file size
        size_kb = asset_data.get("size_kb", 0)
        size_mb = size_kb / 1024.0
        if size_mb > 50:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.WARNING,
                AnalysisScope.ASSET, "Large Asset File",
                f"Asset file size ({size_mb:.1f} MB) is large.",
                "Check for unnecessary detail. Use compressed formats where suitable.",
                asset_id,
            ))

        # Resource: format recommendations
        asset_format = asset_data.get("format", "").lower()
        if asset_type == "texture" and asset_format in ("bmp", "tiff"):
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.ASSET, "Uncompressed Texture Format",
                f"Texture uses {asset_format} format without compression.",
                "Convert to PNG, WebP, or compressed DDS/ASTC for GPU.",
                asset_id,
            ))

        if asset_type == "audio" and asset_format == "wav" and size_mb > 5:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.ASSET, "Uncompressed Audio Asset",
                f"Audio asset is {size_mb:.1f} MB in WAV format.",
                "Convert to OGG, MP3, or ADPCM for in-game use.",
                asset_id,
            ))

        # Visual: naming convention
        asset_name = asset_data.get("name", "")
        if asset_name and " " in asset_name:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.SUGGESTION,
                AnalysisScope.ASSET, "Asset Name Contains Spaces",
                f"Asset '{asset_name}' contains spaces in its name.",
                "Use underscores or camelCase for asset names to avoid cross-platform issues.",
                asset_id,
                auto_fixable=True,
            ))

        # Resource: unused asset detection
        if asset_data.get("reference_count", 1) == 0:
            items.append(self._make_feedback(
                FeedbackCategory.RESOURCE, FeedbackSeverity.SUGGESTION,
                AnalysisScope.ASSET, "Unreferenced Asset",
                f"Asset '{asset_name or asset_id}' is not referenced by any entity.",
                "Remove unused assets to reduce bundle size, or mark as intentionally kept.",
                asset_id,
            ))

        duration_ms = (_time_module.time() - start) * 1000.0
        self._record_analysis(
            AnalysisScope.ASSET, 1, asset_data, duration_ms, items,
        )
        return items

    # ------------------------------------------------------------------
    # Private Heuristic Checkers
    # ------------------------------------------------------------------

    def _check_entity_performance(
        self, entity_id: str, data: Dict[str, Any], items: List[FeedbackItem],
    ) -> None:
        draw_calls = data.get("draw_calls", 0)
        if draw_calls > _DRAW_CALL_CRITICAL:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.CRITICAL,
                AnalysisScope.ENTITY, "Excessive Per-Entity Draw Calls",
                f"Entity generates {draw_calls} draw calls.",
                "Merge sub-meshes, reduce material count, or use GPU instancing.",
                entity_id,
            ))

        memory_kb = data.get("memory_kb", 0)
        if memory_kb > 51200:  # 50 MB
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "High Per-Entity Memory",
                f"Entity uses {memory_kb / 1024:.1f} MB of memory.",
                "Reduce texture resolution or simplify mesh complexity.",
                entity_id,
            ))

        tex_width = data.get("texture_width", 0)
        tex_height = data.get("texture_height", 0)
        if tex_width > _TEXTURE_DIM_WARNING or tex_height > _TEXTURE_DIM_WARNING:
            items.append(self._make_feedback(
                FeedbackCategory.PERFORMANCE, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "Large Textures on Entity",
                f"Entity uses textures up to {tex_width}x{tex_height}.",
                "Downscale textures or use mipmap chains.",
                entity_id,
            ))

    def _check_entity_visual(
        self, entity_id: str, data: Dict[str, Any], items: List[FeedbackItem],
    ) -> None:
        contrast = data.get("contrast_ratio", 10.0)
        if contrast < _CONTRAST_RATIO_MIN:
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "Low Color Contrast",
                f"Entity color contrast ratio is {contrast:.1f}.",
                "Adjust text/foreground colors for better readability against background.",
                entity_id,
            ))

        if data.get("missing_texture", False):
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.ISSUE,
                AnalysisScope.ENTITY, "Missing Texture",
                "Entity references a texture that cannot be resolved.",
                "Assign a valid texture or use a placeholder fallback.",
                entity_id,
                auto_fixable=True,
            ))

        if data.get("overlapping_ui", False):
            items.append(self._make_feedback(
                FeedbackCategory.VISUAL, FeedbackSeverity.SUGGESTION,
                AnalysisScope.ENTITY, "UI Overlap Detected",
                "This UI element overlaps with another element.",
                "Adjust anchor offsets or use a layout group.",
                entity_id,
            ))

    def _check_entity_gameplay(
        self, entity_id: str, data: Dict[str, Any], items: List[FeedbackItem],
    ) -> None:
        stats = data.get("stats", {})
        if stats:
            attack = stats.get("attack", 0)
            defense = stats.get("defense", 0)
            health = stats.get("health", 0)
            values = [v for v in [attack, defense, health] if v > 0]
            if len(values) >= 2:
                mean_val = sum(values) / len(values)
                variance = sum((v - mean_val) ** 2 for v in values) / len(values)
                if variance > (mean_val ** 2) * 0.25:
                    items.append(self._make_feedback(
                        FeedbackCategory.BALANCE, FeedbackSeverity.RECOMMENDATION,
                        AnalysisScope.ENTITY, "Unbalanced Entity Stats",
                        f"Entity stats have high variance (mean={mean_val:.1f}).",
                        "Review stat distribution for competitive balance.",
                        entity_id,
                    ))

        if data.get("spawn_rate_per_min", 0) > 60:
            items.append(self._make_feedback(
                FeedbackCategory.GAMEPLAY, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "High Spawn Rate",
                "This spawner produces entities at a very high rate.",
                "Add a spawn cap or increase cooldown between waves.",
                entity_id,
            ))

    def _check_entity_accessibility(
        self, entity_id: str, data: Dict[str, Any], items: List[FeedbackItem],
    ) -> None:
        font_size = data.get("font_size", 16)
        if 0 < font_size < _FONT_SIZE_MIN:
            items.append(self._make_feedback(
                FeedbackCategory.ACCESSIBILITY, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "Small Font Size",
                f"Text element uses {font_size}px font size.",
                "Increase to at least 14px for readability. Support text scaling.",
                entity_id,
            ))

        if data.get("color_only_indicator", False):
            items.append(self._make_feedback(
                FeedbackCategory.ACCESSIBILITY, FeedbackSeverity.RECOMMENDATION,
                AnalysisScope.ENTITY, "Color-Only Indicator",
                "This element conveys information using color alone.",
                "Add an icon, pattern, or text label alongside the color cue.",
                entity_id,
            ))

        if data.get("is_interactive", False) and not data.get("has_audio_cue", False):
            items.append(self._make_feedback(
                FeedbackCategory.ACCESSIBILITY, FeedbackSeverity.SUGGESTION,
                AnalysisScope.ENTITY, "Missing Audio Cue",
                "Interactive element lacks an audio cue for screen reader or feedback.",
                "Add a hover/click sound for auditory confirmation.",
                entity_id,
            ))

    def _check_entity_code(
        self, entity_id: str, data: Dict[str, Any], items: List[FeedbackItem],
    ) -> None:
        unconnected = data.get("unconnected_events", 0)
        if unconnected > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.WARNING,
                AnalysisScope.ENTITY, "Unconnected Events",
                f"{unconnected} event(s) on this entity have no listeners.",
                "Connect event handlers or remove unused event bindings.",
                entity_id,
            ))

        missing = data.get("missing_references", 0)
        if missing > 0:
            items.append(self._make_feedback(
                FeedbackCategory.CODE, FeedbackSeverity.ISSUE,
                AnalysisScope.ENTITY, "Dangling References",
                f"{missing} references point to missing or deleted entities.",
                "Update references or set up null guards.",
                entity_id,
            ))

    # ------------------------------------------------------------------
    # Feedback Lifecycle
    # ------------------------------------------------------------------

    def apply_fix(self, feedback_id: str) -> bool:
        with self._lock:
            item = self._feedback_items.get(feedback_id)
            if item is None:
                return False
            if item.applied:
                return False
            item.applied = True
            self._total_fixes_applied += 1
            return True

    def dismiss_feedback(self, feedback_id: str) -> bool:
        with self._lock:
            item = self._feedback_items.get(feedback_id)
            if item is None:
                return False
            self._dismissed_ids.add(feedback_id)
            return True

    # ------------------------------------------------------------------
    # Query Methods
    # ------------------------------------------------------------------

    def get_feedback(
        self,
        category: Optional[FeedbackCategory] = None,
        severity: Optional[FeedbackSeverity] = None,
        scope: Optional[AnalysisScope] = None,
        applied: Optional[bool] = None,
    ) -> List[FeedbackItem]:
        with self._lock:
            result = []
            for item in self._feedback_items.values():
                if item.feedback_id in self._dismissed_ids:
                    continue
                if category is not None and item.category != category:
                    continue
                if severity is not None and item.severity != severity:
                    continue
                if scope is not None and item.scope != scope:
                    continue
                if applied is not None and item.applied != applied:
                    continue
                result.append(item)
            result.sort(key=lambda i: _SEVERITY_WEIGHT.get(i.severity.value, 0), reverse=True)
            return result

    def get_feedback_summary(self) -> Dict[str, Any]:
        with self._lock:
            active_items = [
                i for i in self._feedback_items.values()
                if i.feedback_id not in self._dismissed_ids
            ]
            category_counts: Dict[str, int] = {}
            severity_counts: Dict[str, int] = {}
            scope_counts: Dict[str, int] = {}
            applied_count = 0
            auto_fixable_count = 0

            for item in active_items:
                cat = item.category.value
                sev = item.severity.value
                scp = item.scope.value
                category_counts[cat] = category_counts.get(cat, 0) + 1
                severity_counts[sev] = severity_counts.get(sev, 0) + 1
                scope_counts[scp] = scope_counts.get(scp, 0) + 1
                if item.applied:
                    applied_count += 1
                if item.auto_fixable:
                    auto_fixable_count += 1

            critical_count = severity_counts.get(FeedbackSeverity.CRITICAL.value, 0)
            issue_count = severity_counts.get(FeedbackSeverity.ISSUE.value, 0)

            return {
                "total_active": len(active_items),
                "total_generated": self._total_feedback_generated,
                "total_dismissed": len(self._dismissed_ids),
                "applied": applied_count,
                "auto_fixable": auto_fixable_count,
                "critical_count": critical_count,
                "issue_count": issue_count,
                "by_category": category_counts,
                "by_severity": severity_counts,
                "by_scope": scope_counts,
                "focused_categories": sorted(
                    category_counts, key=lambda k: category_counts[k], reverse=True
                )[:3],
            }

    def get_stats(self) -> Dict[str, Any]:
        with self._lock:
            return {
                "total_analyses": self._total_analyses,
                "total_feedback_generated": self._total_feedback_generated,
                "total_fixes_applied": self._total_fixes_applied,
                "total_rules": len(self._rules),
                "enabled_rules": len([r for r in self._rules.values() if r.enabled]),
                "snapshots_stored": len(self._snapshots),
                "feedback_stored": len(self._feedback_items),
                "dismissed": len(self._dismissed_ids),
                "last_analysis_time": self._last_analysis_time,
            }

    # ------------------------------------------------------------------
    # Internal Helpers
    # ------------------------------------------------------------------

    def _make_feedback(
        self,
        category: FeedbackCategory,
        severity: FeedbackSeverity,
        scope: AnalysisScope,
        title: str,
        description: str,
        suggestion: str,
        source_entity: str = "",
        auto_fixable: bool = False,
    ) -> FeedbackItem:
        item = FeedbackItem(
            category=category,
            severity=severity,
            scope=scope,
            title=title,
            description=description,
            suggestion=suggestion,
            source_entity=source_entity,
            auto_fixable=auto_fixable,
        )
        return item

    def _record_analysis(
        self,
        scope: AnalysisScope,
        entities_analyzed: int,
        metrics: Dict[str, Any],
        duration_ms: float,
        items: List[FeedbackItem],
    ) -> None:
        with self._lock:
            self._total_analyses += 1
            self._last_analysis_time = _time_module.time()

            for item in items:
                self._feedback_items[item.feedback_id] = item
                self._total_feedback_generated += 1

                idx_key = f"{item.category.value}:{item.scope.value}"
                if idx_key not in self._feedback_index:
                    self._feedback_index[idx_key] = []
                self._feedback_index[idx_key].append(item.feedback_id)

            snapshot = AnalysisSnapshot(
                scope=scope,
                entities_analyzed=entities_analyzed,
                metrics={
                    k: v for k, v in metrics.items()
                    if isinstance(v, (int, float, str, bool, list, dict))
                },
                duration_ms=round(duration_ms, 2),
            )
            self._snapshots.append(snapshot)

    # ------------------------------------------------------------------
    # Serialization
    # ------------------------------------------------------------------

    def export_feedback(self, include_dismissed: bool = False) -> List[Dict[str, Any]]:
        with self._lock:
            result = []
            for item in self._feedback_items.values():
                if not include_dismissed and item.feedback_id in self._dismissed_ids:
                    continue
                result.append(item.to_dict())
            return result

    def export_rules(self) -> List[Dict[str, Any]]:
        with self._lock:
            return [
                {
                    "rule_id": r.rule_id,
                    "name": r.name,
                    "category": r.category.value,
                    "condition_template": r.condition_template,
                    "suggestion_template": r.suggestion_template,
                    "enabled": r.enabled,
                    "priority": r.priority,
                }
                for r in self._rules.values()
            ]

    def export_json(self, indent: int = 2) -> str:
        data = {
            "stats": self.get_stats(),
            "summary": self.get_feedback_summary(),
            "feedback": self.export_feedback(include_dismissed=False),
        }
        return json.dumps(data, indent=indent)

    def clear_feedback(self) -> int:
        with self._lock:
            count = len(self._feedback_items)
            self._feedback_items.clear()
            self._feedback_index.clear()
            self._dismissed_ids.clear()
            self._snapshots.clear()
            return count


# ---------------------------------------------------------------------------
# Module-level Accessor
# ---------------------------------------------------------------------------


def get_engine_live_feedback() -> LiveFeedbackEngine:
    """Return the global LiveFeedbackEngine singleton instance."""
    return LiveFeedbackEngine.get_instance()