"""
SparkLabs Agent - Game State Intelligence

Real-time game state analysis and optimization system that uses
heuristic analysis to understand gameplay, detect patterns, identify
balancing issues, and suggest optimizations for the AI-native game engine.

Architecture:
  GameStateIntelligence (singleton)
    |-- GameStateSnapshot (point-in-time capture of game state)
    |-- IntelligenceInsight (domain-specific finding with severity)
    |-- Heuristic analyzers (balance, pacing, difficulty, engagement,
    |   economy, progression, accessibility)

Analysis Domains:
  - BALANCE: entity/mechanic fairness across player options
  - PACING: tension-release rhythm and content density
  - DIFFICULTY: challenge ramp matching player skill growth
  - ENGAGEMENT: player retention and interaction quality
  - ECONOMY: resource flow, currency sinks, and reward structures
  - PROGRESSION: unlock sequencing and power curve shaping
  - ACCESSIBILITY: barrier analysis for entry and mastery
"""

from __future__ import annotations

import threading
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Dict, List, Optional


# ------------------------------------------------------------------
# Enums
# ------------------------------------------------------------------


class AnalysisDomain(Enum):
    """Game domain that state intelligence analyzes."""
    BALANCE = "balance"
    PACING = "pacing"
    DIFFICULTY = "difficulty"
    ENGAGEMENT = "engagement"
    ECONOMY = "economy"
    PROGRESSION = "progression"
    ACCESSIBILITY = "accessibility"


class InsightSeverity(Enum):
    """Severity level of an intelligence insight."""
    INFO = "info"
    SUGGESTION = "suggestion"
    WARNING = "warning"
    CRITICAL = "critical"


# ------------------------------------------------------------------
# Dataclasses
# ------------------------------------------------------------------


@dataclass
class GameStateSnapshot:
    """A point-in-time capture of the game state for analysis."""
    snapshot_id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    timestamp: float = field(default_factory=time.time)
    entities: Dict[str, Dict[str, Any]] = field(default_factory=dict)
    metrics: Dict[str, float] = field(default_factory=dict)
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "snapshot_id": self.snapshot_id,
            "timestamp": self.timestamp,
            "entity_count": len(self.entities),
            "metric_count": len(self.metrics),
            "metadata": dict(self.metadata),
        }


@dataclass
class IntelligenceInsight:
    """A domain-specific finding generated by heuristic analysis."""
    insight_id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    domain: AnalysisDomain = AnalysisDomain.BALANCE
    severity: InsightSeverity = InsightSeverity.INFO
    title: str = ""
    description: str = ""
    recommendation: str = ""
    confidence: float = 0.5
    metadata: Dict[str, Any] = field(default_factory=dict)

    def to_dict(self) -> Dict[str, Any]:
        return {
            "insight_id": self.insight_id,
            "domain": self.domain.value,
            "severity": self.severity.value,
            "title": self.title,
            "description": self.description,
            "recommendation": self.recommendation,
            "confidence": self.confidence,
            "metadata": dict(self.metadata),
        }


# ------------------------------------------------------------------
# GameStateIntelligence Singleton
# ------------------------------------------------------------------


class GameStateIntelligence:
    """
    Singleton system for real-time game state analysis and optimization.

    Captures game state snapshots and runs heuristic analysis across
    multiple domains to produce actionable insights about balance,
    pacing, difficulty, engagement, economy, progression, and accessibility.
    """

    _instance: Optional[GameStateIntelligence] = None
    _lock = threading.RLock()

    def __new__(cls) -> GameStateIntelligence:
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    instance = super().__new__(cls)
                    cls._instance = instance
        return cls._instance

    @classmethod
    def get_instance(cls) -> GameStateIntelligence:
        if cls._instance is None:
            with cls._lock:
                if cls._instance is None:
                    instance = super().__new__(cls)
                    instance.__init__()
                    cls._instance = instance
        return cls._instance

    def __init__(self) -> None:
        with self._lock:
            if hasattr(self, "_initialized") and self._initialized:
                return
            self._snapshots: Dict[str, GameStateSnapshot] = {}
            self._insights: Dict[str, IntelligenceInsight] = {}
            self._snapshot_history: deque = deque(maxlen=200)
            self._stats: Dict[str, Any] = {
                "total_snapshots_captured": 0,
                "total_insights_generated": 0,
                "total_analyses_run": 0,
                "insights_by_domain": {d.value: 0 for d in AnalysisDomain},
                "insights_by_severity": {s.value: 0 for s in InsightSeverity},
            }
            self._initialized = True

    # ------------------------------------------------------------------
    # Snapshot Capture
    # ------------------------------------------------------------------

    def capture_snapshot(
        self,
        entities: Dict[str, Dict[str, Any]],
        metrics: Dict[str, float],
        metadata: Optional[Dict[str, Any]] = None,
    ) -> GameStateSnapshot:
        """Capture a point-in-time game state snapshot."""
        with self._lock:
            snapshot = GameStateSnapshot(
                entities=dict(entities),
                metrics=dict(metrics),
                metadata=dict(metadata or {}),
            )
            self._snapshots[snapshot.snapshot_id] = snapshot
            self._snapshot_history.append(snapshot)
            self._stats["total_snapshots_captured"] += 1
            return snapshot

    # ------------------------------------------------------------------
    # Analysis
    # ------------------------------------------------------------------

    def analyze_snapshot(
        self,
        snapshot_id: str,
        domains: Optional[List[AnalysisDomain]] = None,
    ) -> List[IntelligenceInsight]:
        """Run heuristic analysis on a snapshot across specified domains."""
        with self._lock:
            snapshot = self._snapshots.get(snapshot_id)
            if snapshot is None:
                return []
            if domains is None:
                domains = list(AnalysisDomain)

            all_insights: List[IntelligenceInsight] = []
            _analyzers = {
                AnalysisDomain.BALANCE: self._analyze_balance,
                AnalysisDomain.PACING: self._analyze_pacing,
                AnalysisDomain.DIFFICULTY: self._analyze_difficulty,
                AnalysisDomain.ENGAGEMENT: self._analyze_engagement,
                AnalysisDomain.ECONOMY: self._analyze_economy,
                AnalysisDomain.PROGRESSION: self._analyze_progression,
                AnalysisDomain.ACCESSIBILITY: self._analyze_accessibility,
            }
            for domain in domains:
                analyzer = _analyzers.get(domain)
                if analyzer is None:
                    continue
                for insight in analyzer(snapshot):
                    self._insights[insight.insight_id] = insight
                    self._stats["total_insights_generated"] += 1
                    self._stats["insights_by_domain"][insight.domain.value] += 1
                    self._stats["insights_by_severity"][insight.severity.value] += 1
                    all_insights.append(insight)

            self._stats["total_analyses_run"] += 1
            return all_insights

    # ------------------------------------------------------------------
    # Domain Heuristic Analyzers
    # ------------------------------------------------------------------

    def _analyze_balance(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Check entity power ratios and time-to-kill metrics."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        players = [e for e in s.entities.values() if e.get("type") == "player"]
        enemies = [e for e in s.entities.values() if e.get("type") == "enemy"]
        if players and enemies:
            pp = sum(e.get("power", e.get("health", 100)) for e in players)
            ep = sum(e.get("power", e.get("health", 100)) for e in enemies)
            if pp > 0 and ep > 0:
                ratio = pp / ep
                if ratio > 2.0:
                    out.append(IntelligenceInsight(
                        domain=AnalysisDomain.BALANCE, severity=InsightSeverity.WARNING,
                        title="Player power dominance",
                        description=f"Players have {ratio:.1f}x enemy power. Combat too easy.",
                        recommendation="Increase enemy health/damage or reduce player effectiveness.",
                        confidence=min(0.9, 0.5 + ratio * 0.1)))
                elif ratio < 0.5:
                    out.append(IntelligenceInsight(
                        domain=AnalysisDomain.BALANCE, severity=InsightSeverity.CRITICAL,
                        title="Enemy power dominance",
                        description=f"Enemies have {1.0/ratio:.1f}x player power. Frustrating.",
                        recommendation="Reduce enemy stats or provide more player resources.",
                        confidence=min(0.9, 0.5 + (1.0 / ratio) * 0.1)))
        pd = m.get("player_damage", 0)
        eh = m.get("enemy_health", 0)
        if pd > 0 and eh > 0:
            ttk = eh / max(pd, 0.001)
            if ttk < 1.0:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.BALANCE, severity=InsightSeverity.WARNING,
                    title="Time-to-kill too low",
                    description=f"Enemies defeated in {ttk:.2f}s. Combat lacks engagement.",
                    recommendation="Increase enemy health or reduce player damage.",
                    confidence=0.75))
            elif ttk > 30.0:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.BALANCE, severity=InsightSeverity.SUGGESTION,
                    title="Time-to-kill too high",
                    description=f"Enemies take {ttk:.1f}s to defeat. Combat feels tedious.",
                    recommendation="Reduce enemy health or boost player damage.",
                    confidence=0.6))
        return out

    def _analyze_pacing(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Evaluate tension-release rhythm and content density."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        ad = m.get("action_density", 0.5)
        rp = m.get("rest_periods", 0)
        es = m.get("encounter_spacing", 0.0)
        cd = m.get("content_density", 0.5)
        if ad > 0.8 and rp < 2:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PACING, severity=InsightSeverity.WARNING,
                title="High action density without rest",
                description=f"Action density {ad:.2f} with {rp} rest periods. Fatigue risk.",
                recommendation="Insert rest/exploration segments between encounters.",
                confidence=0.7 + ad * 0.15))
        if es > 0 and es < 5.0:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PACING, severity=InsightSeverity.SUGGESTION,
                title="Encounters too close together",
                description=f"{es:.1f}s between encounters. No recovery time.",
                recommendation="Increase spacing between encounters for recovery.",
                confidence=0.65))
        if cd < 0.2:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PACING, severity=InsightSeverity.SUGGESTION,
                title="Low content density",
                description="Long stretches without meaningful content.",
                recommendation="Add more interactive elements, encounters, or narrative beats.",
                confidence=0.55))
        return out

    def _analyze_difficulty(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Assess challenge ramp and player skill alignment."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        ps = m.get("player_skill", 0.5)
        cl = m.get("challenge_level", 0.5)
        dr = m.get("death_rate", 0.0)
        cr = m.get("completion_rate", 1.0)
        if cl > 0 and ps > 0:
            scr = ps / cl
            if scr > 2.0:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.DIFFICULTY, severity=InsightSeverity.WARNING,
                    title="Challenge too low for player skill",
                    description=f"Skill ({ps:.2f}) exceeds challenge ({cl:.2f}). Game trivial.",
                    recommendation="Increase enemy aggression or encounter complexity.",
                    confidence=0.7))
            elif scr < 0.5:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.DIFFICULTY, severity=InsightSeverity.CRITICAL,
                    title="Challenge exceeds player skill",
                    description=f"Challenge ({cl:.2f}) >> skill ({ps:.2f}).",
                    recommendation="Reduce difficulty, add tutorials, or use adaptive scaling.",
                    confidence=0.8))
        if dr > 0.3:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.DIFFICULTY, severity=InsightSeverity.WARNING,
                title="High death rate",
                description=f"Death rate {dr:.1%}. Frustration risk.",
                recommendation="Add checkpoints, reduce damage, improve attack telegraphing.",
                confidence=0.75))
        if cr < 0.5:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.DIFFICULTY, severity=InsightSeverity.WARNING,
                title="Low completion rate",
                description=f"Only {cr:.1%} encounters completed.",
                recommendation="Review encounter design for unfair elements or unclear objectives.",
                confidence=0.7))
        return out

    def _analyze_engagement(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Measure player retention and interaction quality."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        es = m.get("engagement_score", 0.5)
        sl = m.get("session_length", 0)
        ir = m.get("interaction_rate", 1.0)
        it = m.get("idle_time", 0.0)
        if es < 0.3:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ENGAGEMENT, severity=InsightSeverity.WARNING,
                title="Low engagement score",
                description=f"Engagement score {es:.2f}. Players losing interest.",
                recommendation="Introduce varied gameplay, rewards, or narrative hooks.",
                confidence=0.7))
        if sl > 0 and it > 0:
            idle_ratio = it / max(sl, 0.001)
            if idle_ratio > 0.4:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.ENGAGEMENT, severity=InsightSeverity.WARNING,
                    title="High idle time ratio",
                    description=f"Players idle {idle_ratio:.1%} of session.",
                    recommendation="Streamline objectives and reduce downtime.",
                    confidence=0.65))
        if ir < 0.5:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ENGAGEMENT, severity=InsightSeverity.SUGGESTION,
                title="Low interaction rate",
                description="Players not interacting with game systems frequently.",
                recommendation="Increase interactive objects and reduce passive segments.",
                confidence=0.6))
        return out

    def _analyze_economy(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Analyze resource flow, currency sinks, and reward structures."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        rr = m.get("resource_rate", 1.0)
        rs = m.get("resource_spend", 0.0)
        cb = m.get("currency_balance", 0.0)
        sc = m.get("sink_count", 0)
        if rr > 0 and rs > 0:
            flow_ratio = rs / max(rr, 0.001)
            if flow_ratio < 0.3:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.ECONOMY, severity=InsightSeverity.SUGGESTION,
                    title="Resource inflation risk",
                    description=f"Earn {rr:.1f}/s, spend {rs:.1f}/s. Inflation likely.",
                    recommendation="Add resource sinks: upgrades, consumables, cosmetics.",
                    confidence=0.7))
            elif flow_ratio > 2.0:
                out.append(IntelligenceInsight(
                    domain=AnalysisDomain.ECONOMY, severity=InsightSeverity.WARNING,
                    title="Resource scarcity",
                    description=f"Spend {rs:.1f}/s, earn {rr:.1f}/s. Economy punishing.",
                    recommendation="Increase resource generation or reduce costs.",
                    confidence=0.75))
        if sc < 2:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ECONOMY, severity=InsightSeverity.INFO,
                title="Limited resource sinks",
                description=f"Only {sc} resource sinks. Players accumulate unused currency.",
                recommendation="Add diverse spending: upgrades, cosmetics, consumables.",
                confidence=0.6))
        if cb > 1000:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ECONOMY, severity=InsightSeverity.INFO,
                title="High currency accumulation",
                description=f"Average balance {cb:.0f}. No meaningful spending outlets.",
                recommendation="Add high-value purchases or limited-time items.",
                confidence=0.55))
        return out

    def _analyze_progression(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Evaluate unlock sequencing and power curve shaping."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        ps = m.get("progression_speed", 0.5)
        ud = m.get("unlock_density", 0.0)
        pc = m.get("power_curve", 0.5)
        lg = m.get("level_gap", 0)
        if ps > 0.9:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PROGRESSION, severity=InsightSeverity.SUGGESTION,
                title="Progression too fast",
                description=f"Speed {ps:.2f}. Players may exhaust content too quickly.",
                recommendation="Increase XP requirements or add intermediate milestones.",
                confidence=0.65))
        elif ps < 0.2:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PROGRESSION, severity=InsightSeverity.WARNING,
                title="Progression too slow",
                description=f"Speed {ps:.2f}. Players feel stuck or unmotivated.",
                recommendation="Reduce XP requirements, add catch-up mechanics.",
                confidence=0.7))
        if ud < 0.1:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PROGRESSION, severity=InsightSeverity.INFO,
                title="Sparse unlock distribution",
                description="Long stretches without new unlocks.",
                recommendation="Distribute unlocks more evenly across the curve.",
                confidence=0.6))
        if pc > 0.8:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PROGRESSION, severity=InsightSeverity.WARNING,
                title="Steep power curve",
                description=f"Steepness {pc:.2f}. Late-game content inaccessible.",
                recommendation="Flatten power curve while still rewarding progression.",
                confidence=0.65))
        if lg > 5:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.PROGRESSION, severity=InsightSeverity.SUGGESTION,
                title="Large level gap between content",
                description=f"Level gap of {lg} between content tiers.",
                recommendation="Add intermediate content or reduce level requirements.",
                confidence=0.6))
        return out

    def _analyze_accessibility(self, s: GameStateSnapshot) -> List[IntelligenceInsight]:
        """Audit barriers to entry and mastery for diverse players."""
        out: List[IntelligenceInsight] = []
        m = s.metrics
        md = s.metadata
        tc = m.get("tutorial_completion", 1.0)
        ic = m.get("input_complexity", 0.5)
        vc = m.get("visual_clarity", 0.5)
        tv = m.get("text_volume", 0.5)
        if tc < 0.6:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.WARNING,
                title="Low tutorial completion",
                description=f"Only {tc:.1%} complete tutorial. Onboarding inadequate.",
                recommendation="Simplify steps, add interactive practice, offer skip.",
                confidence=0.75))
        if ic > 0.7:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.SUGGESTION,
                title="High input complexity",
                description=f"Input complexity {ic:.2f}. Intimidating for new players.",
                recommendation="Introduce controls gradually, support simpler schemes.",
                confidence=0.7))
        if vc < 0.4:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.WARNING,
                title="Low visual clarity",
                description="Visual info hard to parse for some players.",
                recommendation="Increase contrast, add icon labels, support UI scaling.",
                confidence=0.65))
        if tv > 0.7:
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.INFO,
                title="High text volume",
                description="Dense text may overwhelm players with reading difficulties.",
                recommendation="Chunk text, use visuals, support text-to-speech.",
                confidence=0.55))
        if not md.get("has_subtitles", False):
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.SUGGESTION,
                title="Missing subtitles",
                description="No subtitle support for audio content.",
                recommendation="Add subtitle options for dialogue and audio cues.",
                confidence=0.8))
        if not md.get("has_colorblind_mode", False):
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.SUGGESTION,
                title="No colorblind mode",
                description="Colorblind accessibility options not configured.",
                recommendation="Add colorblind-friendly palettes with shape differentiation.",
                confidence=0.75))
        if not md.get("has_remappable_controls", False):
            out.append(IntelligenceInsight(
                domain=AnalysisDomain.ACCESSIBILITY, severity=InsightSeverity.INFO,
                title="Controls not remappable",
                description="Players cannot customize input bindings.",
                recommendation="Support full control remapping for physical accessibility.",
                confidence=0.7))
        return out

    # ------------------------------------------------------------------
    # Insight Generation
    # ------------------------------------------------------------------

    def generate_insight(
        self,
        domain: AnalysisDomain,
        title: str,
        description: str,
        recommendation: str,
        severity: InsightSeverity = InsightSeverity.INFO,
        confidence: float = 0.5,
        metadata: Optional[Dict[str, Any]] = None,
    ) -> IntelligenceInsight:
        """Manually generate a custom intelligence insight."""
        with self._lock:
            confidence = max(0.0, min(1.0, confidence))
            insight = IntelligenceInsight(
                domain=domain, severity=severity, title=title,
                description=description, recommendation=recommendation,
                confidence=confidence, metadata=dict(metadata or {}))
            self._insights[insight.insight_id] = insight
            self._stats["total_insights_generated"] += 1
            self._stats["insights_by_domain"][insight.domain.value] += 1
            self._stats["insights_by_severity"][insight.severity.value] += 1
            return insight

    # ------------------------------------------------------------------
    # Listing and Filtering
    # ------------------------------------------------------------------

    def list_insights(
        self,
        domain: Optional[AnalysisDomain] = None,
        severity: Optional[InsightSeverity] = None,
        min_confidence: float = 0.0,
    ) -> List[IntelligenceInsight]:
        """List insights filtered by domain, severity, and minimum confidence."""
        results = list(self._insights.values())
        if domain is not None:
            results = [i for i in results if i.domain == domain]
        if severity is not None:
            results = [i for i in results if i.severity == severity]
        if min_confidence > 0.0:
            results = [i for i in results if i.confidence >= min_confidence]
        return results

    def list_snapshots(self) -> List[GameStateSnapshot]:
        """List all captured game state snapshots."""
        return list(self._snapshots.values())

    # ------------------------------------------------------------------
    # Stats
    # ------------------------------------------------------------------

    def get_stats(self) -> Dict[str, Any]:
        """Return aggregate statistics for the game state intelligence engine."""
        with self._lock:
            return {
                "total_snapshots": len(self._snapshots),
                "historical_snapshots": len(self._snapshot_history),
                "total_insights": len(self._insights),
                "total_snapshots_captured": self._stats["total_snapshots_captured"],
                "total_insights_generated": self._stats["total_insights_generated"],
                "total_analyses_run": self._stats["total_analyses_run"],
                "insights_by_domain": dict(self._stats["insights_by_domain"]),
                "insights_by_severity": dict(self._stats["insights_by_severity"]),
            }


# ------------------------------------------------------------------
# Module-level accessor
# ------------------------------------------------------------------


def get_game_state_intelligence() -> GameStateIntelligence:
    """Return the singleton GameStateIntelligence instance."""
    return GameStateIntelligence.get_instance()