"""
SparkLabs Agent - Creative Autonomy Layer"""

from __future__ import annotations

import logging
import threading
import time
import uuid
from collections import deque
from dataclasses import dataclass, field
from enum import Enum
from typing import Any, Deque, Dict, List, Optional, Tuple

logger = logging.getLogger(__name__)


# =============================================================================
# Creative Enums
# =============================================================================

class CreativeGoalType(Enum):
    """Types of creative goals the director can generate."""
    INTRODUCE_MECHANIC = "introduce_mechanic"
    NARRATIVE_EVENT = "narrative_event"
    DIFFICULTY_CURVE = "difficulty_curve"
    REVEAL_CONTENT = "reveal_content"
    SOCIAL_DYNAMIC = "social_dynamic"
    ENVIRONMENTAL_SHIFT = "environmental_shift"
    PROGRESSION_GATE = "progression_gate"


class PatternType(Enum):
    """Detected gameplay patterns that trigger creative goals."""
    ENGAGEMENT_DECLINE = "engagement_decline"
    DIFFICULTY_FLATLINE = "difficulty_flatline"
    CONTENT_STAGNATION = "content_stagnation"
    UNEXPLORED_REGION = "unexplored_region"
    SKILL_PLATEAU = "skill_plateau"
    REPETITIVE_BEHAVIOR = "repetitive_behavior"
    NARRATIVE_GAP = "narrative_gap"
    MASTERY_SURPLUS = "mastery_surplus"
    NONE = "none"


class InterventionPhase(Enum):
    """Phases of a multi-step intervention."""
    SETUP = "setup"
    BUILDUP = "buildup"
    CLIMAX = "climax"
    RESOLUTION = "resolution"
    COMPLETE = "complete"


class GoalStatus(Enum):
    """Status of a creative goal."""
    PROPOSED = "proposed"
    PLANNING = "planning"
    EXECUTING = "executing"
    EVALUATING = "evaluating"
    SUCCESSFUL = "successful"
    ABANDONED = "abandoned"


# =============================================================================
# Data Structures
# =============================================================================

@dataclass
class GameplayPattern:
    """A detected gameplay pattern over a time window."""
    pattern_id: str = field(default_factory=lambda: uuid.uuid4().hex[:10])
    pattern_type: PatternType = PatternType.NONE
    confidence: float = 0.0
    duration_s: float = 0.0
    evidence: Dict[str, float] = field(default_factory=dict)
    detected_at: float = field(default_factory=time.time)
    description: str = ""


@dataclass
class CreativeGoal:
    """A proactive creative goal generated by the autonomy director."""
    goal_id: str = field(default_factory=lambda: uuid.uuid4().hex[:10])
    goal_type: CreativeGoalType = CreativeGoalType.NARRATIVE_EVENT
    trigger_pattern: PatternType = PatternType.NONE
    description: str = ""
    priority: float = 0.5
    created_at: float = field(default_factory=time.time)
    status: GoalStatus = GoalStatus.PROPOSED
    intervention_steps: List["InterventionStep"] = field(default_factory=list)
    current_step_index: int = 0
    predicted_impact: Dict[str, float] = field(default_factory=dict)
    actual_impact: Dict[str, float] = field(default_factory=dict)
    effectiveness: float = 0.0
    target_session_id: str = ""


@dataclass
class InterventionStep:
    """A single step in a multi-step intervention plan."""
    step_id: str = field(default_factory=lambda: uuid.uuid4().hex[:8])
    phase: InterventionPhase = InterventionPhase.SETUP
    action_type: str = ""       # spawn_entity, trigger_event, tune_difficulty, etc.
    params: Dict[str, Any] = field(default_factory=dict)
    delay_s: float = 0.0        # delay after previous step
    executed: bool = False
    executed_at: float = 0.0
    result: Optional[Dict[str, Any]] = None


@dataclass
class CreativePattern:
    """A learned creative pattern that was effective in the past."""
    pattern_id: str = field(default_factory=lambda: uuid.uuid4().hex[:10])
    goal_type: CreativeGoalType = CreativeGoalType.NARRATIVE_EVENT
    trigger_pattern: PatternType = PatternType.NONE
    effectiveness: float = 0.0
    use_count: int = 0
    last_used: float = 0.0
    context_tags: List[str] = field(default_factory=list)


# =============================================================================
# Gameplay Pattern Monitor
# =============================================================================

class GameplayPatternMonitor:
    """Monitors long-term gameplay patterns across minutes of play.

    Collects periodic gameplay snapshots and detects patterns that indicate
    creative opportunities. Unlike the BridgeOrchestrator which works per-frame,
    this works on a longer timescale (every 5-10 seconds).
    """

    def __init__(self) -> None:
        self._engagement_timeline: Deque[Tuple[float, float]] = deque(maxlen=60)
        self._difficulty_timeline: Deque[Tuple[float, float]] = deque(maxlen=60)
        self._variety_timeline: Deque[Tuple[float, float]] = deque(maxlen=60)
        self._exploration_timeline: Deque[Tuple[float, float]] = deque(maxlen=60)
        self._event_diversity: Deque[set] = deque(maxlen=60)
        self._last_snapshot_time: float = 0.0

    def record_snapshot(
        self,
        engagement: float,
        difficulty: float,
        variety: float,
        exploration: float,
        events: List[str],
    ) -> None:
        """Record a periodic gameplay snapshot (call every 5-10s)."""
        now = time.time()
        self._engagement_timeline.append((now, engagement))
        self._difficulty_timeline.append((now, difficulty))
        self._variety_timeline.append((now, variety))
        self._exploration_timeline.append((now, exploration))
        self._event_diversity.append(set(events))
        self._last_snapshot_time = now

    def detect_patterns(self) -> List[GameplayPattern]:
        """Detect gameplay patterns from the collected timeline data."""
        patterns: List[GameplayPattern] = []

        if len(self._engagement_timeline) < 6:
            return patterns  # Not enough data

        # Check for engagement decline
        eng_decline = self._check_engagement_decline()
        if eng_decline:
            patterns.append(eng_decline)

        # Check for difficulty flatline
        diff_flat = self._check_difficulty_flatline()
        if diff_flat:
            patterns.append(diff_flat)

        # Check for content stagnation (low event variety)
        stagnation = self._check_content_stagnation()
        if stagnation:
            patterns.append(stagnation)

        # Check for skill plateau (high skill but low engagement growth)
        skill_plate = self._check_skill_plateau()
        if skill_plate:
            patterns.append(skill_plate)

        # Check for repetitive behavior
        repetitive = self._check_repetitive_behavior()
        if repetitive:
            patterns.append(repetitive)

        # Check for narrative gap (no events for a long time)
        narrative = self._check_narrative_gap()
        if narrative:
            patterns.append(narrative)

        # Check for unexplored region
        unexplored = self._check_unexplored_region()
        if unexplored:
            patterns.append(unexplored)

        return patterns

    def _check_engagement_decline(self) -> Optional[GameplayPattern]:
        """Check if engagement is declining over time."""
        if len(self._engagement_timeline) < 10:
            return None
        recent = [e for _, e in list(self._engagement_timeline)[-5:]]
        older = [e for _, e in list(self._engagement_timeline)[-10:-5]]
        recent_avg = sum(recent) / len(recent)
        older_avg = sum(older) / len(older)
        if recent_avg < older_avg - 0.1 and recent_avg < 0.5:
            return GameplayPattern(
                pattern_type=PatternType.ENGAGEMENT_DECLINE,
                confidence=min(1.0, (older_avg - recent_avg) * 3),
                duration_s=50.0,
                evidence={"recent_avg": recent_avg, "older_avg": older_avg, "delta": recent_avg - older_avg},
                description=f"Engagement declining: {older_avg:.2f} -> {recent_avg:.2f}",
            )
        return None

    def _check_difficulty_flatline(self) -> Optional[GameplayPattern]:
        """Check if difficulty has been flat for too long."""
        if len(self._difficulty_timeline) < 8:
            return None
        recent = [d for _, d in list(self._difficulty_timeline)[-8:]]
        variance = max(recent) - min(recent)
        if variance < 0.05:
            return GameplayPattern(
                pattern_type=PatternType.DIFFICULTY_FLATLINE,
                confidence=min(1.0, (0.1 - variance) * 10),
                duration_s=40.0,
                evidence={"variance": variance, "avg": sum(recent) / len(recent)},
                description=f"Difficulty flat for 8+ samples (variance={variance:.3f})",
            )
        return None

    def _check_content_stagnation(self) -> Optional[GameplayPattern]:
        """Check if event variety is low."""
        if len(self._event_diversity) < 6:
            return None
        recent_sets = list(self._event_diversity)[-6:]
        all_events = set()
        for s in recent_sets:
            all_events |= s
        if len(all_events) < 3:
            return GameplayPattern(
                pattern_type=PatternType.CONTENT_STAGNATION,
                confidence=min(1.0, (3 - len(all_events)) * 0.4),
                duration_s=30.0,
                evidence={"unique_events": len(all_events), "events": list(all_events)},
                description=f"Low event variety: only {len(all_events)} unique events",
            )
        return None

    def _check_skill_plateau(self) -> Optional[GameplayPattern]:
        """Check if player skill has plateaued."""
        if len(self._difficulty_timeline) < 10:
            return None
        recent_diff = [d for _, d in list(self._difficulty_timeline)[-5:]]
        avg_diff = sum(recent_diff) / len(recent_diff)
        if avg_diff > 0.7:
            return GameplayPattern(
                pattern_type=PatternType.SKILL_PLATEAU,
                confidence=0.6,
                duration_s=25.0,
                evidence={"avg_difficulty": avg_diff},
                description="Player skill high but no new challenges introduced",
            )
        return None

    def _check_repetitive_behavior(self) -> Optional[GameplayPattern]:
        """Check if player is repeating the same actions."""
        if len(self._event_diversity) < 5:
            return None
        recent_sets = list(self._event_diversity)[-5:]
        # Check if the same single event dominates
        all_events = []
        for s in recent_sets:
            all_events.extend(list(s))
        if len(all_events) > 0:
            from collections import Counter
            counts = Counter(all_events)
            most_common_ratio = counts.most_common(1)[0][1] / len(all_events)
            if most_common_ratio > 0.7:
                return GameplayPattern(
                    pattern_type=PatternType.REPETITIVE_BEHAVIOR,
                    confidence=most_common_ratio,
                    duration_s=25.0,
                    evidence={"dominant_event": counts.most_common(1)[0][0], "ratio": most_common_ratio},
                    description=f"Repetitive behavior: {counts.most_common(1)[0][0]} dominates",
                )
        return None

    def _check_narrative_gap(self) -> Optional[GameplayPattern]:
        """Check if there's been a lack of narrative events."""
        if len(self._event_diversity) < 4:
            return None
        recent_sets = list(self._event_diversity)[-4:]
        has_narrative = any("narrative" in e or "story" in e or "dialogue" in e for s in recent_sets for e in s)
        if not has_narrative:
            return GameplayPattern(
                pattern_type=PatternType.NARRATIVE_GAP,
                confidence=0.5,
                duration_s=20.0,
                evidence={"has_narrative": False},
                description="No narrative events detected in recent play",
            )
        return None

    def _check_unexplored_region(self) -> Optional[GameplayPattern]:
        """Check if exploration radius has stagnated."""
        if len(self._exploration_timeline) < 6:
            return None
        recent = [e for _, e in list(self._exploration_timeline)[-3:]]
        older = [e for _, e in list(self._exploration_timeline)[-6:-3]]
        recent_avg = sum(recent) / len(recent)
        older_avg = sum(older) / len(older)
        if abs(recent_avg - older_avg) < 10 and recent_avg < 500:
            return GameplayPattern(
                pattern_type=PatternType.UNEXPLORED_REGION,
                confidence=0.4,
                duration_s=30.0,
                evidence={"exploration_radius": recent_avg},
                description="Player not expanding exploration radius",
            )
        return None


# =============================================================================
# Creative Goal Generator
# =============================================================================

class CreativeGoalGenerator:
    """Generates creative goals from detected gameplay patterns.

    Each pattern type maps to one or more creative goal types. The generator
    prioritizes goals based on pattern confidence, player state, and the
    historical effectiveness of similar goals.
    """

    # Pattern -> Goal type mapping
    PATTERN_GOAL_MAP = {
        PatternType.ENGAGEMENT_DECLINE: [
            CreativeGoalType.NARRATIVE_EVENT,
            CreativeGoalType.ENVIRONMENTAL_SHIFT,
            CreativeGoalType.INTRODUCE_MECHANIC,
        ],
        PatternType.DIFFICULTY_FLATLINE: [
            CreativeGoalType.DIFFICULTY_CURVE,
            CreativeGoalType.PROGRESSION_GATE,
        ],
        PatternType.CONTENT_STAGNATION: [
            CreativeGoalType.INTRODUCE_MECHANIC,
            CreativeGoalType.REVEAL_CONTENT,
            CreativeGoalType.ENVIRONMENTAL_SHIFT,
        ],
        PatternType.SKILL_PLATEAU: [
            CreativeGoalType.PROGRESSION_GATE,
            CreativeGoalType.DIFFICULTY_CURVE,
        ],
        PatternType.REPETITIVE_BEHAVIOR: [
            CreativeGoalType.INTRODUCE_MECHANIC,
            CreativeGoalType.REVEAL_CONTENT,
        ],
        PatternType.NARRATIVE_GAP: [
            CreativeGoalType.NARRATIVE_EVENT,
            CreativeGoalType.SOCIAL_DYNAMIC,
        ],
        PatternType.UNEXPLORED_REGION: [
            CreativeGoalType.REVEAL_CONTENT,
            CreativeGoalType.ENVIRONMENTAL_SHIFT,
        ],
        PatternType.MASTERY_SURPLUS: [
            CreativeGoalType.DIFFICULTY_CURVE,
            CreativeGoalType.PROGRESSION_GATE,
        ],
    }

    # Goal descriptions
    GOAL_DESCRIPTIONS = {
        CreativeGoalType.INTRODUCE_MECHANIC: "Introduce a new gameplay mechanic to refresh engagement",
        CreativeGoalType.NARRATIVE_EVENT: "Trigger a narrative event to advance the story",
        CreativeGoalType.DIFFICULTY_CURVE: "Reshape the difficulty curve for better pacing",
        CreativeGoalType.REVEAL_CONTENT: "Reveal hidden or unexplored content",
        CreativeGoalType.SOCIAL_DYNAMIC: "Introduce an NPC interaction or faction event",
        CreativeGoalType.ENVIRONMENTAL_SHIFT: "Transform the environment dynamically",
        CreativeGoalType.PROGRESSION_GATE: "Create a meaningful progression checkpoint",
    }

    def __init__(self) -> None:
        self._creative_memory: Dict[str, CreativePattern] = {}
        self._goal_history: Deque[CreativeGoal] = deque(maxlen=50)

    def generate(
        self,
        patterns: List[GameplayPattern],
        session_id: str = "",
    ) -> List[CreativeGoal]:
        """Generate creative goals from detected patterns."""
        goals: List[CreativeGoal] = []

        for pattern in patterns:
            goal_types = self.PATTERN_GOAL_MAP.get(pattern.pattern_type, [])
            for goal_type in goal_types:
                # Check if we already have an active goal of this type
                if any(g.goal_type == goal_type and g.status in (
                    GoalStatus.PROPOSED, GoalStatus.PLANNING, GoalStatus.EXECUTING
                ) for g in goals):
                    continue

                # Calculate priority based on pattern confidence and past effectiveness
                base_priority = pattern.confidence * 0.6
                past_effect = self._get_past_effectiveness(goal_type, pattern.pattern_type)
                priority = min(1.0, base_priority + past_effect * 0.3)

                goal = CreativeGoal(
                    goal_type=goal_type,
                    trigger_pattern=pattern.pattern_type,
                    description=self.GOAL_DESCRIPTIONS.get(goal_type, ""),
                    priority=priority,
                    target_session_id=session_id,
                    predicted_impact=self._predict_impact(goal_type, pattern),
                )
                goals.append(goal)

        # Sort by priority
        goals.sort(key=lambda g: g.priority, reverse=True)
        return goals

    def _get_past_effectiveness(
        self,
        goal_type: CreativeGoalType,
        trigger: PatternType,
    ) -> float:
        """Get the historical effectiveness of a goal type for a trigger."""
        key = f"{goal_type.value}:{trigger.value}"
        pattern = self._creative_memory.get(key)
        return pattern.effectiveness if pattern else 0.3

    def _predict_impact(
        self,
        goal_type: CreativeGoalType,
        pattern: GameplayPattern,
    ) -> Dict[str, float]:
        """Predict the impact of a creative intervention."""
        # Base predictions on goal type
        predictions = {
            "engagement_delta": 0.0,
            "variety_delta": 0.0,
            "difficulty_delta": 0.0,
        }

        if goal_type == CreativeGoalType.INTRODUCE_MECHANIC:
            predictions["engagement_delta"] = 0.2
            predictions["variety_delta"] = 0.3
        elif goal_type == CreativeGoalType.NARRATIVE_EVENT:
            predictions["engagement_delta"] = 0.15
            predictions["variety_delta"] = 0.2
        elif goal_type == CreativeGoalType.DIFFICULTY_CURVE:
            predictions["difficulty_delta"] = 0.15
            predictions["engagement_delta"] = 0.1
        elif goal_type == CreativeGoalType.REVEAL_CONTENT:
            predictions["engagement_delta"] = 0.1
            predictions["variety_delta"] = 0.25
        elif goal_type == CreativeGoalType.ENVIRONMENTAL_SHIFT:
            predictions["engagement_delta"] = 0.15
            predictions["variety_delta"] = 0.2
        elif goal_type == CreativeGoalType.PROGRESSION_GATE:
            predictions["engagement_delta"] = 0.1
            predictions["difficulty_delta"] = 0.1
        elif goal_type == CreativeGoalType.SOCIAL_DYNAMIC:
            predictions["engagement_delta"] = 0.12
            predictions["variety_delta"] = 0.15

        # Modulate by pattern confidence
        for k in predictions:
            predictions[k] *= pattern.confidence

        return predictions

    def record_outcome(self, goal: CreativeGoal) -> None:
        """Record the outcome of a creative goal for future learning."""
        self._goal_history.append(goal)
        key = f"{goal.goal_type.value}:{goal.trigger_pattern.value}"
        current = self._creative_memory.get(key)
        if current is None:
            current = CreativePattern(
                goal_type=goal.goal_type,
                trigger_pattern=goal.trigger_pattern,
                effectiveness=goal.effectiveness,
                use_count=1,
                last_used=time.time(),
            )
        else:
            # Exponential moving average
            alpha = 0.3
            current.effectiveness = alpha * goal.effectiveness + (1 - alpha) * current.effectiveness
            current.use_count += 1
            current.last_used = time.time()
        self._creative_memory[key] = current

    def get_memory_stats(self) -> List[Dict[str, Any]]:
        """Get creative memory statistics."""
        return [
            {
                "goal_type": p.goal_type.value,
                "trigger": p.trigger_pattern.value,
                "effectiveness": round(p.effectiveness, 3),
                "use_count": p.use_count,
            }
            for p in self._creative_memory.values()
        ]


# =============================================================================
# Intervention Planner
# =============================================================================

class InterventionPlanner:
    """Plans multi-step intervention sequences for creative goals.

    Each creative goal is decomposed into a sequence of intervention steps
    that unfold over time (setup -> buildup -> climax -> resolution).
    This makes creative interventions feel natural rather than abrupt.
    """

    def plan_intervention(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Create a multi-step intervention plan for a creative goal."""
        if goal.goal_type == CreativeGoalType.INTRODUCE_MECHANIC:
            return self._plan_mechanic_introduction(goal)
        elif goal.goal_type == CreativeGoalType.NARRATIVE_EVENT:
            return self._plan_narrative_event(goal)
        elif goal.goal_type == CreativeGoalType.DIFFICULTY_CURVE:
            return self._plan_difficulty_curve(goal)
        elif goal.goal_type == CreativeGoalType.REVEAL_CONTENT:
            return self._plan_content_reveal(goal)
        elif goal.goal_type == CreativeGoalType.ENVIRONMENTAL_SHIFT:
            return self._plan_environmental_shift(goal)
        elif goal.goal_type == CreativeGoalType.PROGRESSION_GATE:
            return self._plan_progression_gate(goal)
        elif goal.goal_type == CreativeGoalType.SOCIAL_DYNAMIC:
            return self._plan_social_dynamic(goal)
        return []

    def _plan_mechanic_introduction(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a new mechanic introduction: hint -> tutorial -> challenge."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "mechanic_hint", "message": "Something glints in the distance..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="spawn_entity",
                params={"category": "tutorial_item", "position": "ahead", "count": 1},
                delay_s=5.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "mechanic_tutorial", "message": "New ability unlocked!"},
                delay_s=8.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="spawn_entity",
                params={"category": "challenge_obstacle", "count": 2, "requires_new_mechanic": True},
                delay_s=12.0,
            ),
        ]

    def _plan_narrative_event(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a narrative event: foreshadow -> build -> reveal -> consequence."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "foreshadow", "message": "A rumble echoes from the east..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="trigger_event",
                params={"event": "buildup", "message": "The ground trembles. Something approaches."},
                delay_s=6.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "narrative_climax", "message": "A mysterious figure emerges!"},
                delay_s=10.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="spawn_entity",
                params={"category": "narrative_npc", "count": 1, "interactive": True},
                delay_s=14.0,
            ),
        ]

    def _plan_difficulty_curve(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a difficulty curve adjustment: measure -> adjust -> verify."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="adjust_pacing",
                params={"action": "measure", "duration_s": 10},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="tune_difficulty",
                params={"direction": "increase", "magnitude": 0.15},
                delay_s=5.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="spawn_entity",
                params={"category": "elite_enemy", "count": 1},
                delay_s=10.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="tune_difficulty",
                params={"direction": "normalize", "magnitude": 0.05},
                delay_s=15.0,
            ),
        ]

    def _plan_content_reveal(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a content reveal: hint -> guide -> discover -> reward."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "discovery_hint", "message": "A faint path leads somewhere new..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="spawn_entity",
                params={"category": "guide_marker", "count": 1},
                delay_s=4.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "area_reveal", "message": "A hidden chamber opens!"},
                delay_s=8.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="spawn_entity",
                params={"category": "treasure", "count": 1, "rare": True},
                delay_s=12.0,
            ),
        ]

    def _plan_environmental_shift(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan an environmental transformation: warning -> shift -> adapt."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "env_warning", "message": "The atmosphere begins to change..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="tune_physics",
                params={"property": "gravity", "change": "subtle"},
                delay_s=5.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "env_shift", "message": "The world transforms around you!"},
                delay_s=10.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="spawn_entity",
                params={"category": "env_hazard", "count": 2},
                delay_s=14.0,
            ),
        ]

    def _plan_progression_gate(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a progression checkpoint: challenge -> gate -> reward."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "gate_appearance", "message": "A sealed gate blocks your path..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="spawn_entity",
                params={"category": "gate_guardian", "count": 1, "elite": True},
                delay_s=6.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "gate_challenge", "message": "Defeat the guardian to proceed!"},
                delay_s=10.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="trigger_event",
                params={"event": "gate_open", "message": "The gate swings open!"},
                delay_s=16.0,
            ),
        ]

    def _plan_social_dynamic(self, goal: CreativeGoal) -> List[InterventionStep]:
        """Plan a social/NPC interaction: approach -> dialogue -> outcome."""
        return [
            InterventionStep(
                phase=InterventionPhase.SETUP,
                action_type="trigger_event",
                params={"event": "npc_approach", "message": "Someone calls out to you..."},
                delay_s=0.0,
            ),
            InterventionStep(
                phase=InterventionPhase.BUILDUP,
                action_type="spawn_entity",
                params={"category": "npc", "count": 1, "interactive": True, "dialogue": True},
                delay_s=4.0,
            ),
            InterventionStep(
                phase=InterventionPhase.CLIMAX,
                action_type="trigger_event",
                params={"event": "dialogue_exchange", "message": "The NPC shares important information."},
                delay_s=8.0,
            ),
            InterventionStep(
                phase=InterventionPhase.RESOLUTION,
                action_type="spawn_entity",
                params={"category": "quest_item", "count": 1},
                delay_s=12.0,
            ),
        ]


# =============================================================================
# Creative Autonomy Director
# =============================================================================

class CreativeAutonomyDirector:
    """
    The singleton director that orchestrates proactive creative intelligence
    during live gameplay. It monitors long-term patterns, generates creative
    goals, plans multi-step interventions, and learns from outcomes.

    This is the creative counterpart to the BridgeOrchestrator (reactive)
    and the AgentEngineFusionLoop (engine optimization). Together, the three
    form the complete AI-native agent intelligence:

    - BridgeOrchestrator: per-frame reactive adaptation
    - AgentEngineFusionLoop: engine performance optimization
    - CreativeAutonomyDirector: proactive creative content generation
    """

    _instance: Optional["CreativeAutonomyDirector"] = None
    _instance_lock = threading.Lock()

    def __init__(self) -> None:
        self._lock = threading.RLock()
        self._pattern_monitor = GameplayPatternMonitor()
        self._goal_generator = CreativeGoalGenerator()
        self._intervention_planner = InterventionPlanner()

        # Active state
        self._active_goals: Dict[str, CreativeGoal] = {}
        self._completed_goals: Deque[CreativeGoal] = deque(maxlen=50)
        self._last_pattern_check: float = 0.0
        self._pattern_check_interval_s: float = 10.0  # Check patterns every 10s
        self._last_intervention_check: float = 0.0
        self._intervention_check_interval_s: float = 2.0  # Check interventions every 2s

        # Statistics
        self._total_patterns_detected: int = 0
        self._total_goals_generated: int = 0
        self._total_interventions_planned: int = 0
        self._total_steps_executed: int = 0
        self._total_successful_goals: int = 0
        self._total_abandoned_goals: int = 0

        # Session tracking
        self._session_id: str = ""
        self._snapshot_count: int = 0

    @classmethod
    def get_instance(cls) -> "CreativeAutonomyDirector":
        if cls._instance is None:
            with cls._instance_lock:
                if cls._instance is None:
                    cls._instance = cls()
        return cls._instance

    # -------------------------------------------------------------------------
    # Public API
    # -------------------------------------------------------------------------

    def record_gameplay_snapshot(
        self,
        engagement: float,
        difficulty: float,
        variety: float,
        exploration: float,
        events: List[str],
        session_id: str = "",
    ) -> None:
        """Record a periodic gameplay snapshot for pattern detection.

        Call this every 5-10 seconds from the bridge or game loop.
        """
        with self._lock:
            self._session_id = session_id or self._session_id
            self._pattern_monitor.record_snapshot(
                engagement, difficulty, variety, exploration, events
            )
            self._snapshot_count += 1

    def check_and_generate(self) -> List[CreativeGoal]:
        """Check for patterns and generate creative goals if needed.

        Returns any newly generated goals. Call this periodically.
        """
        with self._lock:
            now = time.time()
            if now - self._last_pattern_check < self._pattern_check_interval_s:
                return []

            self._last_pattern_check = now

            # Detect patterns
            patterns = self._pattern_monitor.detect_patterns()
            self._total_patterns_detected += len(patterns)

            if not patterns:
                return []

            # Generate goals
            new_goals = self._goal_generator.generate(patterns, self._session_id)
            self._total_goals_generated += len(new_goals)

            # Plan interventions for new goals
            for goal in new_goals:
                goal.intervention_steps = self._intervention_planner.plan_intervention(goal)
                goal.status = GoalStatus.PLANNING
                self._total_interventions_planned += len(goal.intervention_steps)
                self._active_goals[goal.goal_id] = goal

            return new_goals

    def get_pending_steps(self, session_id: str = "") -> List[Tuple[str, InterventionStep]]:
        """Get intervention steps that are ready to execute.

        Returns a list of (goal_id, step) tuples for steps whose delay
        has elapsed and haven't been executed yet.
        """
        with self._lock:
            now = time.time()
            pending: List[Tuple[str, InterventionStep]] = []

            for goal in list(self._active_goals.values()):
                if goal.status not in (GoalStatus.PLANNING, GoalStatus.EXECUTING):
                    continue

                goal.status = GoalStatus.EXECUTING
                steps = goal.intervention_steps

                for i, step in enumerate(steps):
                    if step.executed:
                        continue
                    if i < goal.current_step_index:
                        continue

                    # Check delay
                    if i == 0:
                        ready = True
                    else:
                        prev_step = steps[i - 1]
                        if prev_step.executed:
                            ready = now - prev_step.executed_at >= step.delay_s
                        else:
                            ready = False

                    if ready:
                        pending.append((goal.goal_id, step))
                        goal.current_step_index = i
                        break  # One step per goal per check

            return pending

    def mark_step_executed(
        self,
        goal_id: str,
        step_id: str,
        result: Dict[str, Any],
    ) -> None:
        """Mark an intervention step as executed."""
        with self._lock:
            goal = self._active_goals.get(goal_id)
            if not goal:
                return

            for step in goal.intervention_steps:
                if step.step_id == step_id:
                    step.executed = True
                    step.executed_at = time.time()
                    step.result = result
                    self._total_steps_executed += 1
                    break

            # Check if all steps are complete
            if all(s.executed for s in goal.intervention_steps):
                goal.status = GoalStatus.EVALUATING

    def evaluate_goal(self, goal_id: str, impact: Dict[str, float]) -> None:
        """Evaluate the outcome of a completed creative goal."""
        with self._lock:
            goal = self._active_goals.get(goal_id)
            if not goal:
                return

            goal.actual_impact = impact

            # Calculate effectiveness as average of predicted vs actual alignment
            if goal.predicted_impact:
                total_delta = 0.0
                count = 0
                for key, predicted in goal.predicted_impact.items():
                    actual = impact.get(key, 0.0)
                    if predicted > 0:
                        # Positive prediction: effectiveness = actual / predicted
                        total_delta += min(1.0, actual / predicted) if predicted > 0 else 0.0
                    else:
                        # No prediction: use actual directly
                        total_delta += min(1.0, max(0.0, actual))
                    count += 1
                goal.effectiveness = total_delta / count if count > 0 else 0.0
            else:
                # No predictions: use average of actual impacts
                vals = [v for v in impact.values() if isinstance(v, (int, float))]
                goal.effectiveness = sum(vals) / len(vals) if vals else 0.0

            # Mark goal as successful or abandoned
            if goal.effectiveness > 0.2:
                goal.status = GoalStatus.SUCCESSFUL
                self._total_successful_goals += 1
            else:
                goal.status = GoalStatus.ABANDONED
                self._total_abandoned_goals += 1

            # Record in creative memory
            self._goal_generator.record_outcome(goal)

            # Move to completed
            self._completed_goals.append(goal)
            del self._active_goals[goal_id]

    def status(self) -> Dict[str, Any]:
        """Get the creative autonomy director status."""
        with self._lock:
            return {
                "session_id": self._session_id,
                "snapshot_count": self._snapshot_count,
                "active_goals": len(self._active_goals),
                "completed_goals": len(self._completed_goals),
                "total_patterns_detected": self._total_patterns_detected,
                "total_goals_generated": self._total_goals_generated,
                "total_interventions_planned": self._total_interventions_planned,
                "total_steps_executed": self._total_steps_executed,
                "total_successful_goals": self._total_successful_goals,
                "total_abandoned_goals": self._total_abandoned_goals,
                "success_rate": (
                    self._total_successful_goals / max(1, self._total_successful_goals + self._total_abandoned_goals)
                ),
                "creative_memory": self._goal_generator.get_memory_stats(),
            }

    def get_active_goals(self) -> List[Dict[str, Any]]:
        """Get currently active creative goals."""
        with self._lock:
            return [
                {
                    "goal_id": g.goal_id,
                    "goal_type": g.goal_type.value,
                    "trigger_pattern": g.trigger_pattern.value,
                    "description": g.description,
                    "priority": round(g.priority, 3),
                    "status": g.status.value,
                    "current_step": g.current_step_index,
                    "total_steps": len(g.intervention_steps),
                    "predicted_impact": g.predicted_impact,
                    "effectiveness": round(g.effectiveness, 3),
                    "steps": [
                        {
                            "step_id": s.step_id,
                            "phase": s.phase.value,
                            "action_type": s.action_type,
                            "params": s.params,
                            "delay_s": s.delay_s,
                            "executed": s.executed,
                        }
                        for s in g.intervention_steps
                    ],
                }
                for g in self._active_goals.values()
            ]

    def get_completed_goals(self, limit: int = 20) -> List[Dict[str, Any]]:
        """Get recently completed creative goals."""
        with self._lock:
            goals = list(self._completed_goals)[-limit:]
        return [
            {
                "goal_id": g.goal_id,
                "goal_type": g.goal_type.value,
                "trigger_pattern": g.trigger_pattern.value,
                "description": g.description,
                "status": g.status.value,
                "effectiveness": round(g.effectiveness, 3),
                "predicted_impact": g.predicted_impact,
                "actual_impact": g.actual_impact,
            }
            for g in goals
        ]

    def reset(self) -> None:
        """Reset the creative autonomy director state."""
        with self._lock:
            self._pattern_monitor = GameplayPatternMonitor()
            self._goal_generator = CreativeGoalGenerator()
            self._intervention_planner = InterventionPlanner()
            self._active_goals.clear()
            self._completed_goals.clear()
            self._total_patterns_detected = 0
            self._total_goals_generated = 0
            self._total_interventions_planned = 0
            self._total_steps_executed = 0
            self._total_successful_goals = 0
            self._total_abandoned_goals = 0
            self._snapshot_count = 0
            self._session_id = ""


# =============================================================================
# Module-level convenience
# =============================================================================

def get_creative_director() -> CreativeAutonomyDirector:
    """Get the singleton creative autonomy director."""
    return CreativeAutonomyDirector.get_instance()
